"""B-splines and convolution.

B-splines of increasing order are generated by successive convolution of
the box function B0 = 1 on [-1/2, 1/2].

Credit: Nick Trefethen, July 2012.
Original MATLAB Chebfun: https://www.chebfun.org/examples/approx/BSplineConv.html
"""

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import jax.numpy as jnp
import numpy as np
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'src'))

import chebfunjax as cj
from chebfunjax.plotting import chebfun_style
chebfun_style()


_OUTDIR = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       '..', '..', 'docs', 'images', 'approx')


def run():
    os.makedirs(_OUTDIR, exist_ok=True)

    # B0 = characteristic function on [-0.5, 0.5]
    B0 = cj.chebfun(lambda x: jnp.ones_like(x), domain=(-0.5, 0.5))

    splines = [B0]
    for _ in range(4):
        splines.append(splines[-1].conv(B0))

    fig, axes = plt.subplots(1, 5, figsize=(15, 4))
    ax_range = [-3, 3, -0.2, 1.2]

    for i, Bi in enumerate(splines):
        ax = axes[i]
        xx = np.linspace(ax_range[0], ax_range[1], 600)
        vals = np.array([float(Bi(jnp.array(x)))
                         if ax_range[0] <= x <= ax_range[1] else 0.0
                         for x in xx])
        ax.plot(xx, vals, 'b', lw=1.8)
        ax.set_xlim(ax_range[0], ax_range[1])
        ax.set_ylim(ax_range[2], ax_range[3])
        ax.grid(True, alpha=0.3)
        ax.set_title(f'B-spline order {i}', fontsize=10)
        ax.set_xlabel('x')

    fig.suptitle('B-splines via successive convolution with B0', fontsize=12)
    fig.tight_layout()
    fig.savefig(os.path.join(_OUTDIR, 'BSplineConv.png'), dpi=150)
    plt.close(fig)

    print(f"BSplineConv: generated {len(splines)} B-splines.")
    return True


if __name__ == '__main__':
    run()
