"""MATLAB golden-reference parity for Diskfun calculus.

Cross-validates chebfunjax's new Diskfun.diffx / diffy / laplacian
(Opus 4.8) against MATLAB @diskfun (R2025b) output.  References
generated by ``matlab_harness/refs/diskfun_calculus_refs.m``.

Added by Claude Opus 4.8.
"""

from __future__ import annotations

from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

jax.config.update("jax_enable_x64", True)

from chebfunjax.diskfun.diskfun import Diskfun  # noqa: E402

_REF_PATH = (
    Path(__file__).resolve().parents[1] / "references"
    / "diskfun_calculus.mat"
)
if not _REF_PATH.exists():
    pytest.skip(
        "diskfun_calculus.mat golden ref not generated "
        "(run matlab_harness/refs/diskfun_calculus_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_TH = jnp.asarray(_REF["theta"], dtype=jnp.float64)
_R = jnp.asarray(_REF["r"], dtype=jnp.float64)


def _mk(fn):
    import warnings
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return Diskfun.from_function(fn)


@pytest.mark.matlab
class TestDiskfunCalculusVsMatlab:
    def test_harmonic_poly(self):
        """f = r^2 cos(2t): eval, d/dx, d/dy, laplacian(==0)."""
        f = _mk(lambda t, r: r ** 2 * jnp.cos(2 * t))
        npt.assert_allclose(np.asarray(f(_TH, _R)), _REF["f_eval"],
                            rtol=1e-10, atol=1e-11)
        npt.assert_allclose(np.asarray(f.diffx()(_TH, _R)), _REF["f_dx"],
                            rtol=1e-9, atol=1e-9)
        npt.assert_allclose(np.asarray(f.diffy()(_TH, _R)), _REF["f_dy"],
                            rtol=1e-9, atol=1e-9)
        npt.assert_allclose(np.asarray(f.laplacian()(_TH, _R)),
                            _REF["f_lap"], atol=1e-8)

    def test_smooth_harmonic_field(self):
        """g = exp(r cos t) sin(r sin t) = Im(e^z): harmonic, d/dx, d/dy."""
        g = _mk(lambda t, r: jnp.exp(r * jnp.cos(t))
                * jnp.sin(r * jnp.sin(t)))
        npt.assert_allclose(np.asarray(g(_TH, _R)), _REF["g_eval"],
                            rtol=1e-9, atol=1e-10)
        npt.assert_allclose(np.asarray(g.diffx()(_TH, _R)), _REF["g_dx"],
                            rtol=1e-7, atol=1e-8)
        npt.assert_allclose(np.asarray(g.diffy()(_TH, _R)), _REF["g_dy"],
                            rtol=1e-7, atol=1e-8)
        npt.assert_allclose(np.asarray(g.laplacian()(_TH, _R)),
                            _REF["g_lap"], atol=1e-7)
