"""MATLAB golden-reference parity tests for the diskfun module.

chebfunjax Diskfun is polar-native (f(theta, r), theta in [-pi,pi], r in [0,1]),
so the MATLAB refs are built in 'polar' mode. Pins evaluation, sum2 (integral
over the unit disk) and numerical rank at rtol 1e-12. Golden ref generated by
matlab_harness/refs/diskfun.m (-> tests/references/diskfun.mat).
"""

from pathlib import Path

import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

from chebfunjax.diskfun.diskfun import Diskfun

_REF_PATH = Path(__file__).resolve().parents[1] / "references" / "diskfun.mat"
if not _REF_PATH.exists():
    pytest.skip(
        "diskfun.mat golden ref not generated (run matlab_harness/refs/diskfun.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_T = jnp.asarray(_REF["tpts"], dtype=jnp.float64)
_R = jnp.asarray(_REF["rpts"], dtype=jnp.float64)

# Same polar battery as matlab_harness/refs/diskfun.m.
_FUNS = {
    1: lambda t, r: r**2,
    2: lambda t, r: r * jnp.cos(t),
    3: lambda t, r: jnp.exp(r * jnp.cos(t)),
    4: lambda t, r: 1 + (r * jnp.cos(t)) * (r * jnp.sin(t)),
}
RTOL = 1e-12


@pytest.mark.matlab
@pytest.mark.parametrize(
    "i",
    [
        1,
        2,
        # f3 = exp(x): previously xfailed (rank 3 vs MATLAB 13, ~3% eval
        # error) — fixed by correcting the GE pivot flat-index conversion
        # to numpy row-major order and removing the 1e4*eps tolerance floor.
        3,
        4,
    ],
)
class TestDiskfunVsMatlab:
    def test_eval(self, i):
        f = Diskfun.from_function(_FUNS[i])
        npt.assert_allclose(np.asarray(f(_T, _R)), _REF[f"f{i}_eval"],
                            rtol=RTOL, atol=1e-12)

    def test_sum(self, i):
        f = Diskfun.from_function(_FUNS[i])
        npt.assert_allclose(float(f.sum()), float(_REF[f"f{i}_sum"]),
                            rtol=RTOL, atol=1e-12)

    def test_rank(self, i):
        f = Diskfun.from_function(_FUNS[i])
        assert int(f.rank) == int(_REF[f"f{i}_rank"])
