"""MATLAB golden-reference parity for the Diskfun Poisson solver.

Cross-validates chebfunjax's Diskfun.poisson (Opus 4.8) against MATLAB
diskfun.poisson (R2025b) with homogeneous Dirichlet BC, plus a
manufactured exact solution.  References generated by
``matlab_harness/refs/diskfun_poisson_refs.m``.

Added by Claude Opus 4.8.
"""

from __future__ import annotations

from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

jax.config.update("jax_enable_x64", True)

from chebfunjax.diskfun.diskfun import Diskfun  # noqa: E402

_REF_PATH = (
    Path(__file__).resolve().parents[1] / "references"
    / "diskfun_poisson.mat"
)
if not _REF_PATH.exists():
    pytest.skip(
        "diskfun_poisson.mat golden ref not generated "
        "(run matlab_harness/refs/diskfun_poisson_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_TH = jnp.asarray(_REF["theta"], dtype=jnp.float64)
_R = jnp.asarray(_REF["r"], dtype=jnp.float64)


@pytest.mark.matlab
class TestDiskfunPoissonVsMatlab:
    def test_smooth_rhs(self):
        """laplacian(u) = r^2 cos(2t), u=0 on r=1, vs MATLAB."""
        u = Diskfun.poisson(lambda t, r: r ** 2 * jnp.cos(2 * t), m=48)
        npt.assert_allclose(np.asarray(u(_TH, _R)), _REF["u1_vals"],
                            rtol=1e-8, atol=1e-9)

    def test_manufactured_solution(self):
        """f = -12 r^2 cos(2t): exact solution u = (1-r^2) r^2 cos(2t)."""
        u = Diskfun.poisson(lambda t, r: -12 * r ** 2 * jnp.cos(2 * t),
                            m=48)
        got = np.asarray(u(_TH, _R))
        npt.assert_allclose(got, _REF["u2_vals"], rtol=1e-8, atol=1e-9)
        # and the analytic exact solution
        exact = (1 - np.asarray(_R) ** 2) * np.asarray(_R) ** 2 \
            * np.cos(2 * np.asarray(_TH))
        npt.assert_allclose(got, exact, atol=1e-9)


class TestDiskfunPoissonManufactured:
    """Analytic manufactured-solution checks (no MATLAB needed)."""

    def test_radial_modes(self):
        T, R = jnp.meshgrid(jnp.linspace(-3.0, 3.0, 7),
                            jnp.linspace(0.1, 0.95, 7))
        Tr, Rr = T.ravel(), R.ravel()
        for m in (0, 1, 2, 3):
            # f = -4(m+1) r^m cos(m t) -> u = (1-r^2) r^m cos(m t)
            u = Diskfun.poisson(
                lambda t, r, _m=m: -4 * (_m + 1) * r ** _m
                * jnp.cos(_m * t), m=30)
            got = np.asarray(u(Tr, Rr))
            want = (1 - np.asarray(Rr) ** 2) * np.asarray(Rr) ** m \
                * np.cos(m * np.asarray(Tr))
            npt.assert_allclose(got, want, atol=1e-10)
