"""MATLAB golden-reference parity tests for the chebfun2d (Chebfun2) module.

Pins evaluation, sum2 (double integral), Frobenius norm, and numerical rank
against MATLAB Chebfun2 at rtol 1e-12.  Golden ref generated by
matlab_harness/refs/chebfun2d.m (-> tests/references/chebfun2d.mat).
"""

from pathlib import Path

import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

import chebfunjax as cj

_REF_PATH = Path(__file__).resolve().parents[1] / "references" / "chebfun2d.mat"
if not _REF_PATH.exists():
    pytest.skip(
        "chebfun2d.mat golden ref not generated (run matlab_harness/refs/chebfun2d.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_PX = jnp.asarray(_REF["pts_x"], dtype=jnp.float64)
_PY = jnp.asarray(_REF["pts_y"], dtype=jnp.float64)
_QX = jnp.asarray(_REF["qx"], dtype=jnp.float64)
_QY = jnp.asarray(_REF["qy"], dtype=jnp.float64)

# Same battery as matlab_harness/refs/chebfun2d.m, on the default domain.
_FUNS = {
    1: lambda x, y: jnp.cos(x) * jnp.sin(y),
    2: lambda x, y: jnp.exp(x + y),
    3: lambda x, y: 1.0 / (1.0 + x**2 + 2 * y**2),
    4: lambda x, y: x**2 - y**2 + x * y,
}

RTOL = 1e-12


@pytest.mark.matlab
@pytest.mark.parametrize("i", [1, 2, 3, 4])
class TestChebfun2VsMatlab:
    def test_eval(self, i):
        f = cj.chebfun2(_FUNS[i])
        got = np.asarray(f(_PX, _PY))
        npt.assert_allclose(got, _REF[f"f{i}_eval"], rtol=RTOL, atol=1e-13)

    def test_sum2(self, i):
        f = cj.chebfun2(_FUNS[i])
        npt.assert_allclose(float(f.sum2()), float(_REF[f"f{i}_sum2"]),
                            rtol=RTOL, atol=1e-12)

    def test_norm(self, i):
        f = cj.chebfun2(_FUNS[i])
        npt.assert_allclose(float(f.norm()), float(_REF[f"f{i}_norm"]), rtol=RTOL)

    def test_rank(self, i):
        # Ranks match MATLAB exactly since the ACA stopping tolerance was
        # made the faithful getTol translation (gradient-aware, grid^(2/3)
        # scaling); the old max(eps*vscale, 1e4*eps) formula was ~300x
        # looser and stopped one pivot early on 1/(1+x^2+2y^2).
        f = cj.chebfun2(_FUNS[i])
        assert int(f.rank) == int(_REF[f"f{i}_rank"])


@pytest.mark.matlab
class TestChebfun2NonUnitDomain:
    def _g(self):
        return cj.chebfun2(lambda x, y: jnp.sin(3 * x) + jnp.cos(2 * y),
                           domain=tuple(float(v) for v in _REF["dom"]))

    def test_eval(self):
        npt.assert_allclose(np.asarray(self._g()(_QX, _QY)), _REF["g_eval"],
                            rtol=RTOL, atol=1e-13)

    def test_sum2(self):
        npt.assert_allclose(float(self._g().sum2()), float(_REF["g_sum2"]), rtol=RTOL)

    def test_norm(self):
        npt.assert_allclose(float(self._g().norm()), float(_REF["g_norm"]), rtol=RTOL)

    def test_rank(self):
        assert int(self._g().rank) == int(_REF["g_rank"])
