"""Expanded MATLAB golden-reference parity for Chebfun2.

Adds partial derivatives, double integrals, norms and rank on richer
functions beyond the basic chebfun2d ref, cross-validated against
MATLAB @chebfun2 (R2025b).  References generated by
``matlab_harness/refs/chebfun2_extras_refs.m``.

Added by Claude Opus 4.8.
"""

from __future__ import annotations

from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

jax.config.update("jax_enable_x64", True)

from chebfunjax.chebfun2d.chebfun2 import Chebfun2  # noqa: E402

_REF_PATH = (
    Path(__file__).resolve().parents[1] / "references" / "chebfun2_extras.mat"
)
if not _REF_PATH.exists():
    pytest.skip(
        "chebfun2_extras.mat golden ref not generated "
        "(run matlab_harness/refs/chebfun2_extras_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_X = jnp.asarray(_REF["X"], dtype=jnp.float64)
_Y = jnp.asarray(_REF["Y"], dtype=jnp.float64)


def _mk(fn):
    return Chebfun2.from_function(fn, domain=(-1.0, 1.0, -1.0, 1.0))


@pytest.mark.matlab
class TestChebfun2ExtrasVsMatlab:
    def test_f_eval_and_calculus(self):
        """f = exp(x) sin(2y): eval, sum2, norm, rank, d/dx, d/dy."""
        f = _mk(lambda x, y: jnp.exp(x) * jnp.sin(2 * y))
        npt.assert_allclose(np.asarray(f(_X, _Y)), _REF["f_eval"],
                            rtol=1e-11, atol=1e-11)
        # sum2 = 0 exactly (sin(2y) is odd on [-1,1]); compare with atol
        npt.assert_allclose(float(f.sum2()), float(_REF["f_sum2"]),
                            rtol=1e-11, atol=1e-13)
        npt.assert_allclose(float(f.norm()), float(_REF["f_norm"]),
                            rtol=1e-10)
        assert int(f.rank) == int(_REF["f_rank"])
        # diff(dim=2) is d/dx, diff(dim=1) is d/dy (MATLAB convention)
        npt.assert_allclose(np.asarray(f.diff(2)(_X, _Y)), _REF["f_dx"],
                            rtol=1e-9, atol=1e-9)
        npt.assert_allclose(np.asarray(f.diff(1)(_X, _Y)), _REF["f_dy"],
                            rtol=1e-9, atol=1e-9)

    def test_g_eval_and_calculus(self):
        """g = cos(3xy) + x."""
        g = _mk(lambda x, y: jnp.cos(3 * x * y) + x)
        npt.assert_allclose(np.asarray(g(_X, _Y)), _REF["g_eval"],
                            rtol=1e-11, atol=1e-11)
        npt.assert_allclose(float(g.sum2()), float(_REF["g_sum2"]),
                            rtol=1e-11)
        npt.assert_allclose(float(g.norm()), float(_REF["g_norm"]),
                            rtol=1e-10)
        npt.assert_allclose(np.asarray(g.diff(2)(_X, _Y)), _REF["g_dx"],
                            rtol=1e-9, atol=1e-9)
        npt.assert_allclose(np.asarray(g.diff(1)(_X, _Y)), _REF["g_dy"],
                            rtol=1e-9, atol=1e-9)

    def test_harmonic_laplacian(self):
        """h = exp(x) cos(y) is harmonic: h_xx + h_yy == 0."""
        h = _mk(lambda x, y: jnp.exp(x) * jnp.cos(y))
        lap = np.asarray(h.diff(2, 2)(_X, _Y)) + np.asarray(
            h.diff(1, 2)(_X, _Y))
        npt.assert_allclose(lap, _REF["h_lap"], atol=1e-8)
        npt.assert_allclose(lap, np.zeros_like(lap), atol=1e-8)
