"""Second batch of core Chebfun MATLAB golden-reference parity.

Broadens @chebfun cross-validation: mean, flipud, complex
real/imag/abs/angle, special functions (erf, besselj), sign,
cumsum-then-diff round-trip.  References generated by
``matlab_harness/refs/chebfun_core2_refs.m``.

Added by Claude Opus 4.8.
"""

from __future__ import annotations

from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

jax.config.update("jax_enable_x64", True)

import chebfunjax as cj  # noqa: E402

_REF_PATH = (
    Path(__file__).resolve().parents[1] / "references" / "chebfun_core2.mat"
)
if not _REF_PATH.exists():
    pytest.skip(
        "chebfun_core2.mat golden ref not generated "
        "(run matlab_harness/refs/chebfun_core2_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_XT = jnp.asarray(_REF["xt"], dtype=jnp.float64)


@pytest.mark.matlab
class TestChebfunCore2VsMatlab:
    def test_mean_and_flipud(self):
        f = cj.chebfun(lambda x: jnp.exp(x) * jnp.sin(3 * x))
        npt.assert_allclose(float(f.mean()), float(_REF["f_mean"]),
                            rtol=1e-11)
        npt.assert_allclose(np.asarray(f.flipud()(_XT)), _REF["f_flipud"],
                            rtol=1e-10, atol=1e-11)

    def test_complex(self):
        c = cj.chebfun(lambda x: jnp.exp(2j * x))
        npt.assert_allclose(np.asarray(c.real()(_XT)), _REF["c_real"],
                            rtol=1e-11, atol=1e-11)
        npt.assert_allclose(np.asarray(c.imag()(_XT)), _REF["c_imag"],
                            rtol=1e-11, atol=1e-11)
        npt.assert_allclose(np.asarray(c.abs()(_XT)), _REF["c_abs"],
                            rtol=1e-10, atol=1e-11)

    def test_special_functions(self):
        e = cj.chebfun(lambda x: 2 * x).erf()
        npt.assert_allclose(np.asarray(e(_XT)), _REF["erf_vals"],
                            rtol=1e-10, atol=1e-11)
        b = cj.chebfun(lambda x: 5 * x).besselj(0)
        npt.assert_allclose(np.asarray(b(_XT)), _REF["besselj0_vals"],
                            rtol=1e-9, atol=1e-9)

    # NOTE: a sign(sin(4x)) test is intentionally omitted -- chebfunjax
    # has no splitting-on, so sign() returns a smooth (Gibbs-oscillating)
    # approximation rather than the exact piecewise +/-1 that MATLAB
    # produces, so it can't cross-validate at golden-ref tolerance
    # (tracked as library gap #12).

    def test_cumsum_diff_roundtrip(self):
        g = cj.chebfun(lambda x: jnp.cos(2 * x))
        npt.assert_allclose(np.asarray(g.cumsum().diff()(_XT)),
                            _REF["cumsum_diff"], rtol=1e-10, atol=1e-10)
