"""MATLAB golden-reference parity for core Chebfun (1D) operations.

Cross-validates chebfunjax's ``Chebfun`` against MATLAB Chebfun's
``@chebfun`` at machine precision across the operations its 166-file
test suite exercises: construction, evaluation, calculus, roots,
min/max, norms, abs, arithmetic, composition, restrict.  References
generated by ``matlab_harness/refs/chebfun_core_refs.m``.

Added by Claude Opus 4.8 to broaden core-class cross-validation beyond
the pre-existing basic sin/exp construction ref.
"""

from __future__ import annotations

from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

jax.config.update("jax_enable_x64", True)

import chebfunjax as cj  # noqa: E402

_REF_PATH = (
    Path(__file__).resolve().parents[1] / "references" / "chebfun_core.mat"
)
if not _REF_PATH.exists():
    pytest.skip(
        "chebfun_core.mat golden ref not generated "
        "(run matlab_harness/refs/chebfun_core_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)

RTOL = 1e-12
ATOL = 1e-12
_XT = jnp.asarray(_REF["xt"], dtype=jnp.float64)


def _f():
    return cj.chebfun(lambda x: jnp.exp(x) * jnp.sin(5 * x))


@pytest.mark.matlab
class TestChebfunCoreVsMatlab:
    def test_eval(self):
        npt.assert_allclose(np.asarray(_f()(_XT)), _REF["f_vals"],
                            rtol=RTOL, atol=ATOL)

    def test_sum(self):
        npt.assert_allclose(float(_f().sum()), float(_REF["f_sum"]),
                            rtol=RTOL, atol=ATOL)

    def test_diff(self):
        npt.assert_allclose(np.asarray(_f().diff()(_XT)), _REF["f_diff"],
                            rtol=1e-11, atol=1e-11)

    def test_diff2(self):
        npt.assert_allclose(np.asarray(_f().diff(2)(_XT)), _REF["f_diff2"],
                            rtol=1e-10, atol=1e-10)

    def test_cumsum(self):
        npt.assert_allclose(np.asarray(_f().cumsum()(_XT)),
                            _REF["f_cumsum"], rtol=1e-11, atol=1e-11)

    def test_norms(self):
        f = _f()
        npt.assert_allclose(float(f.norm()), float(_REF["f_norm2"]),
                            rtol=RTOL)
        npt.assert_allclose(float(f.norm(1)), float(_REF["f_norm1"]),
                            rtol=1e-11)
        npt.assert_allclose(float(f.norm(np.inf)),
                            float(_REF["f_norminf"]), rtol=1e-10)

    def test_roots(self):
        g = cj.chebfun(lambda x: jnp.sin(6 * x))
        r = np.sort(np.asarray(g.roots()))
        want = np.sort(np.atleast_1d(np.asarray(_REF["g_roots"])))
        assert len(r) == len(want)
        npt.assert_allclose(r, want, atol=1e-11)

    def test_min_max(self):
        # chebfunjax min()/max() return (x_extremum, f_extremum);
        # MATLAB [val, loc] = min(f) stores val and loc separately.
        h = cj.chebfun(lambda x: x ** 3 - x)
        xmin, fmin = h.min()
        xmax, fmax = h.max()
        npt.assert_allclose(float(fmin), float(_REF["h_min"]), atol=1e-11)
        npt.assert_allclose(float(xmin), float(_REF["h_minx"]), atol=1e-9)
        npt.assert_allclose(float(fmax), float(_REF["h_max"]), atol=1e-11)
        npt.assert_allclose(float(xmax), float(_REF["h_maxx"]), atol=1e-9)

    def test_abs(self):
        absf = abs(cj.chebfun(lambda x: jnp.sin(3 * x)))
        npt.assert_allclose(np.asarray(absf(_XT)), _REF["abs_vals"],
                            rtol=1e-11, atol=1e-11)
        npt.assert_allclose(float(absf.sum()), float(_REF["abs_sum"]),
                            rtol=1e-10)

    def test_arithmetic(self):
        p = cj.chebfun(lambda x: 1 + x ** 2)
        q = cj.chebfun(lambda x: jnp.cos(2 * x))
        npt.assert_allclose(np.asarray((p + q)(_XT)), _REF["pq_plus"],
                            rtol=RTOL, atol=ATOL)
        npt.assert_allclose(np.asarray((p - q)(_XT)), _REF["pq_minus"],
                            rtol=RTOL, atol=ATOL)
        npt.assert_allclose(np.asarray((p * q)(_XT)), _REF["pq_times"],
                            rtol=RTOL, atol=ATOL)
        npt.assert_allclose(np.asarray((p / (2 + q))(_XT)),
                            _REF["pq_rdiv"], rtol=1e-11, atol=1e-11)

    def test_composition(self):
        u = cj.chebfun(lambda x: 0.5 * x)
        npt.assert_allclose(np.asarray(u.exp()(_XT)), _REF["exp_u"],
                            rtol=RTOL, atol=ATOL)
        npt.assert_allclose(np.asarray(u.sin()(_XT)), _REF["sin_u"],
                            rtol=RTOL, atol=ATOL)
        w = cj.chebfun(lambda x: 3 * x)
        npt.assert_allclose(np.asarray(w.tanh()(_XT)), _REF["tanh_u"],
                            rtol=1e-11, atol=1e-11)

    def test_restrict_sum(self):
        w = cj.chebfun(lambda x: jnp.exp(x))
        wr = w.restrict(-0.5, 0.5)
        npt.assert_allclose(float(wr.sum()), float(_REF["restrict_sum"]),
                            rtol=1e-12)

    def test_inner_product(self):
        f = _f()
        g = cj.chebfun(lambda x: jnp.sin(6 * x))
        npt.assert_allclose(float((f * g).sum()), float(_REF["f_dot_g"]),
                            rtol=1e-11, atol=1e-12)
