"""Tests for Chebfun arithmetic, calculus, rootfinding, and extrema.

JAX contract
------------
- Arithmetic (f+g, f*g, etc.)   jit=yes (single-piece), vmap=yes
- diff(k)                        jit=yes, vmap=yes
- cumsum()                       jit=yes
- sum()                          jit=yes
- inner(g)                       jit=yes
- norm()                         jit=yes
- mean()                         jit=yes
- roots()                        jit=NO  (variable output size)
- max(), min(), minandmax()      jit=NO  (uses roots of derivative)

MATLAB golden refs: tests/references/chebfun_ops.mat  (generated by
matlab_harness/generate_refs_ops.m once MATLAB is available).
"""

from __future__ import annotations

import jax
import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest

from chebfunjax.chebfun1d.chebfun import Chebfun, chebfun

# Standard tolerances for spectral accuracy (float64)
RTOL = 1e-12
ATOL = 1e-12


# ============================================================================
# Tier 1: Arithmetic
# ============================================================================


class TestChebfunArithmetic:
    """Tests for +, -, *, /, **, abs, unary -, unary +.

    JAX contract: jit=yes (single-piece), vmap=yes.
    """

    def test_add_chebfun_chebfun(self):
        """(sin + cos)(x) == sin(x) + cos(x) pointwise."""
        f = chebfun(jnp.sin)
        g = chebfun(jnp.cos)
        h = f + g
        xs = jnp.linspace(-1.0, 1.0, 40, dtype=jnp.float64)
        expected = jnp.sin(xs) + jnp.cos(xs)
        npt.assert_allclose(np.array(h(xs)), np.array(expected), rtol=RTOL, atol=ATOL)

    def test_add_scalar(self):
        """(sin + 2)(x) == sin(x) + 2 pointwise."""
        f = chebfun(jnp.sin)
        h = f + 2.0
        xs = jnp.linspace(-1.0, 1.0, 30, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(h(xs)), np.array(jnp.sin(xs) + 2.0), rtol=RTOL, atol=ATOL
        )

    def test_radd_scalar(self):
        """2 + sin should equal sin + 2."""
        f = chebfun(jnp.sin)
        h = 2.0 + f
        xs = jnp.linspace(-1.0, 1.0, 20, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(h(xs)), np.array(jnp.sin(xs) + 2.0), rtol=RTOL, atol=ATOL
        )

    def test_sub_chebfun_chebfun(self):
        """(sin - cos)(x) == sin(x) - cos(x)."""
        f = chebfun(jnp.sin)
        g = chebfun(jnp.cos)
        h = f - g
        xs = jnp.linspace(-1.0, 1.0, 30, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(h(xs)), np.array(jnp.sin(xs) - jnp.cos(xs)), rtol=RTOL, atol=ATOL
        )

    def test_sub_scalar(self):
        """sin - 1 should subtract 1 from every value."""
        f = chebfun(jnp.sin)
        h = f - 1.0
        x = jnp.float64(0.5)
        npt.assert_allclose(float(h(x)), float(jnp.sin(x)) - 1.0, atol=1e-13)

    def test_rsub_scalar(self):
        """1 - sin should work."""
        f = chebfun(jnp.sin)
        h = 1.0 - f
        x = jnp.float64(0.5)
        npt.assert_allclose(float(h(x)), 1.0 - float(jnp.sin(x)), atol=1e-13)

    def test_neg(self):
        """(-sin)(x) == -sin(x)."""
        f = chebfun(jnp.sin)
        h = -f
        xs = jnp.linspace(-1.0, 1.0, 20, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(h(xs)), np.array(-jnp.sin(xs)), rtol=RTOL, atol=ATOL
        )

    def test_pos(self):
        """+f is f."""
        f = chebfun(jnp.sin)
        h = +f
        xs = jnp.linspace(-1.0, 1.0, 10, dtype=jnp.float64)
        npt.assert_allclose(np.array(h(xs)), np.array(f(xs)), atol=1e-15)

    def test_mul_chebfun_chebfun(self):
        """(sin * sin)(x) == sin(x)^2."""
        f = chebfun(jnp.sin)
        h = f * f
        xs = jnp.linspace(-1.0, 1.0, 40, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(h(xs)), np.array(jnp.sin(xs) ** 2), rtol=RTOL, atol=ATOL
        )

    def test_mul_scalar(self):
        """(sin * 3)(x) == 3*sin(x)."""
        f = chebfun(jnp.sin)
        h = f * 3.0
        xs = jnp.linspace(-1.0, 1.0, 20, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(h(xs)), np.array(3.0 * jnp.sin(xs)), rtol=RTOL, atol=ATOL
        )

    def test_rmul_scalar(self):
        """3 * sin should equal sin * 3."""
        f = chebfun(jnp.sin)
        h = 3.0 * f
        xs = jnp.linspace(-1.0, 1.0, 20, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(h(xs)), np.array(3.0 * jnp.sin(xs)), rtol=RTOL, atol=ATOL
        )

    def test_truediv_scalar(self):
        """sin / 2 should halve sin."""
        f = chebfun(jnp.sin)
        h = f / 2.0
        xs = jnp.linspace(-1.0, 1.0, 20, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(h(xs)), np.array(jnp.sin(xs) / 2.0), rtol=RTOL, atol=ATOL
        )

    def test_truediv_chebfun(self):
        """sin / exp should give sin(x)/exp(x)."""
        f = chebfun(jnp.sin)
        g = chebfun(jnp.exp)
        h = f / g
        xs = jnp.linspace(-0.9, 0.9, 30, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(h(xs)),
            np.array(jnp.sin(xs) / jnp.exp(xs)),
            rtol=1e-10,
            atol=1e-10,
        )

    def test_rtruediv_scalar(self):
        """1 / exp should give exp(-x)."""
        g = chebfun(jnp.exp)
        h = 1.0 / g
        xs = jnp.linspace(-0.9, 0.9, 20, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(h(xs)),
            np.array(1.0 / jnp.exp(xs)),
            rtol=1e-10,
            atol=1e-10,
        )

    def test_pow_integer(self):
        """sin^2 == sin * sin."""
        f = chebfun(jnp.sin)
        h = f ** 2
        xs = jnp.linspace(-1.0, 1.0, 30, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(h(xs)), np.array(jnp.sin(xs) ** 2), rtol=RTOL, atol=ATOL
        )

    def test_pow_zero(self):
        """sin^0 == 1."""
        f = chebfun(jnp.sin)
        h = f ** 0
        xs = jnp.linspace(-1.0, 1.0, 10, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(h(xs)), np.ones(10), atol=1e-14
        )

    def test_pow_chebfun(self):
        """exp^sin should give exp(x)^sin(x)."""
        f = chebfun(jnp.exp)
        g = chebfun(jnp.sin)
        h = f ** g
        xs = jnp.linspace(-0.5, 0.5, 20, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(h(xs)),
            np.array(jnp.exp(xs) ** jnp.sin(xs)),
            rtol=1e-10,
            atol=1e-10,
        )

    def test_abs(self):
        """abs(sin) is non-negative and returns a Chebfun.

        Note: abs(sin) has a kink at sin's zeros (x=0 on [-1,1]).
        The current implementation evaluates on a fine grid and re-interpolates
        (from Chebtech2.__abs__), so the result is a smooth polynomial
        approximation to a non-smooth function.  Accuracy is limited by the
        kink and is NOT expected to be spectral.

        This test checks:
          1. The result is a Chebfun.
          2. All values are non-negative.
          3. At the left and right endpoints (far from the kink), it matches
             |sin| closely.
        """
        f = chebfun(jnp.sin)
        h = abs(f)
        assert isinstance(h, Chebfun)
        # Non-negativity
        xs = jnp.linspace(-1.0, 1.0, 40, dtype=jnp.float64)
        vals = np.array(h(xs))
        assert np.all(vals >= -1e-5), f"abs(sin) has negative values: min={vals.min()}"
        # At endpoints (far from the zero at x=0), match should be decent
        x_end = jnp.array([-1.0, 1.0], dtype=jnp.float64)
        npt.assert_allclose(
            np.array(h(x_end)),
            np.abs(np.array(jnp.sin(x_end))),
            rtol=1e-5,
            atol=1e-5,
        )

    def test_domain_mismatch_raises(self):
        """Adding two Chebfuns on different domains should raise ValueError."""
        f = chebfun(jnp.sin, domain=[-1, 1])
        g = chebfun(jnp.sin, domain=[0, 1])
        with pytest.raises(ValueError, match="domains do not match"):
            _ = f + g

    def test_multipiece_add(self):
        """Adding two 2-piece Chebfuns piece-wise."""
        f = chebfun(jnp.sin, domain=[-1, 0, 1])
        g = chebfun(jnp.cos, domain=[-1, 0, 1])
        h = f + g
        assert len(h.funs) == 2
        xs = jnp.linspace(-1.0, 1.0, 40, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(h(xs)),
            np.array(jnp.sin(xs) + jnp.cos(xs)),
            rtol=RTOL,
            atol=ATOL,
        )

    def test_custom_domain_arithmetic(self):
        """Arithmetic on [0, pi] domain should work correctly."""
        f = chebfun(jnp.sin, domain=[0, jnp.pi])
        g = chebfun(jnp.cos, domain=[0, jnp.pi])
        h = f + g
        xs = jnp.linspace(0.0, float(jnp.pi), 30, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(h(xs)),
            np.array(jnp.sin(xs) + jnp.cos(xs)),
            rtol=RTOL,
            atol=ATOL,
        )

    # JAX contract tests for arithmetic
    def test_add_jit(self):
        """Addition result is JIT-safe (single-piece)."""
        import equinox as eqx
        f = chebfun(jnp.sin)
        g = chebfun(jnp.cos)
        h = f + g
        jit_h = eqx.filter_jit(h)
        xs = jnp.linspace(-1.0, 1.0, 20, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(jit_h(xs)),
            np.array((f + g)(xs)),
            atol=1e-14,
        )

    def test_mul_jit(self):
        """Multiplication result is JIT-safe (single-piece)."""
        import equinox as eqx
        f = chebfun(jnp.sin)
        g = chebfun(jnp.cos)
        h = f * g
        jit_h = eqx.filter_jit(h)
        xs = jnp.linspace(-1.0, 1.0, 20, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(jit_h(xs)),
            np.array(jnp.sin(xs) * jnp.cos(xs)),
            rtol=RTOL,
            atol=ATOL,
        )


# ============================================================================
# Tier 2: Calculus — differentiation
# ============================================================================


class TestChebfunDiff:
    """Tests for Chebfun.diff().

    JAX contract: jit=yes (k static), vmap=yes.
    """

    def test_sin_diff_matches_cos(self):
        """d/dx [sin(x)] ≈ cos(x) at machine precision."""
        f = chebfun(jnp.sin)
        fp = f.diff()
        xs = jnp.linspace(-1.0, 1.0, 40, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(fp(xs)), np.array(jnp.cos(xs)), rtol=RTOL, atol=ATOL
        )

    def test_cos_diff_matches_neg_sin(self):
        """d/dx [cos(x)] == -sin(x)."""
        f = chebfun(jnp.cos)
        fp = f.diff()
        xs = jnp.linspace(-1.0, 1.0, 30, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(fp(xs)), np.array(-jnp.sin(xs)), rtol=RTOL, atol=ATOL
        )

    def test_exp_diff_matches_exp(self):
        """d/dx [exp(x)] == exp(x)."""
        f = chebfun(jnp.exp)
        fp = f.diff()
        xs = jnp.linspace(-1.0, 1.0, 30, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(fp(xs)), np.array(jnp.exp(xs)), rtol=RTOL, atol=ATOL
        )

    def test_second_derivative(self):
        """d^2/dx^2 [sin(x)] == -sin(x)."""
        f = chebfun(jnp.sin)
        fpp = f.diff(2)
        xs = jnp.linspace(-1.0, 1.0, 30, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(fpp(xs)), np.array(-jnp.sin(xs)), rtol=RTOL, atol=ATOL
        )

    def test_diff_at_specific_point(self):
        """f.diff()(0.5) ≈ cos(0.5) — spec example from task."""
        f = chebfun(jnp.sin)
        dfdx = f.diff()
        npt.assert_allclose(
            float(dfdx(jnp.float64(0.5))),
            float(jnp.cos(jnp.float64(0.5))),
            rtol=1e-13,
        )

    def test_diff_zeroth_order_is_identity(self):
        """diff(0) returns self (no-op)."""
        f = chebfun(jnp.sin)
        g = f.diff(0)
        xs = jnp.linspace(-1.0, 1.0, 10, dtype=jnp.float64)
        npt.assert_allclose(np.array(g(xs)), np.array(f(xs)), atol=1e-15)

    def test_diff_custom_domain(self):
        """d/dx [sin(x)] on [0, pi] should match cos(x)."""
        f = chebfun(jnp.sin, domain=[0, jnp.pi])
        fp = f.diff()
        xs = jnp.linspace(0.0, float(jnp.pi), 30, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(fp(xs)), np.array(jnp.cos(xs)), rtol=RTOL, atol=ATOL
        )

    def test_diff_multipiece(self):
        """Piecewise Chebfun diff should match pointwise derivative."""
        f = chebfun(jnp.sin, domain=[-1, 0, 1])
        fp = f.diff()
        xs = jnp.array([-0.8, -0.5, -0.2, 0.2, 0.5, 0.8], dtype=jnp.float64)
        npt.assert_allclose(
            np.array(fp(xs)), np.array(jnp.cos(xs)), rtol=1e-10, atol=1e-10
        )

    def test_diff_jit(self):
        """Differentiation result is JIT-safe."""
        import equinox as eqx
        f = chebfun(jnp.sin)
        fp = f.diff()
        jit_fp = eqx.filter_jit(fp)
        xs = jnp.linspace(-1.0, 1.0, 20, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(jit_fp(xs)), np.array(jnp.cos(xs)), rtol=RTOL, atol=ATOL
        )


# ============================================================================
# Tier 3: Calculus — cumsum
# ============================================================================


class TestChebfunCumsum:
    """Tests for Chebfun.cumsum().

    JAX contract: jit=yes.
    """

    def test_cumsum_of_cos_is_sin_minus_sin_a(self):
        """cumsum(cos) on [-1, 1] should be sin(x) - sin(-1)."""
        f = chebfun(jnp.cos)
        F = f.cumsum()
        xs = jnp.linspace(-1.0, 1.0, 40, dtype=jnp.float64)
        expected = jnp.sin(xs) - jnp.sin(jnp.float64(-1.0))
        npt.assert_allclose(
            np.array(F(xs)), np.array(expected), rtol=RTOL, atol=ATOL
        )

    def test_cumsum_left_endpoint_is_zero(self):
        """F(a) = 0 for any Chebfun."""
        f = chebfun(jnp.sin)
        F = f.cumsum()
        val = float(F(jnp.float64(-1.0)))
        npt.assert_allclose(val, 0.0, atol=1e-13)

    def test_cumsum_custom_domain(self):
        """cumsum of sin on [0, pi]: F(x) = -cos(x) + cos(0) = 1 - cos(x)."""
        f = chebfun(jnp.sin, domain=[0, jnp.pi])
        F = f.cumsum()
        xs = jnp.linspace(0.0, float(jnp.pi), 30, dtype=jnp.float64)
        expected = 1.0 - jnp.cos(xs)
        npt.assert_allclose(
            np.array(F(xs)), np.array(expected), rtol=RTOL, atol=ATOL
        )

    def test_cumsum_then_diff_recovers_f(self):
        """(cumsum(f)).diff() == f pointwise (fundamental theorem of calculus)."""
        f = chebfun(jnp.exp)
        F = f.cumsum()
        Fp = F.diff()
        xs = jnp.linspace(-0.9, 0.9, 30, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(Fp(xs)), np.array(jnp.exp(xs)), rtol=1e-10, atol=1e-10
        )

    def test_cumsum_multipiece_continuity(self):
        """Piecewise cumsum should be continuous at breakpoints.

        We check by evaluating F at the breakpoint x=0 from both pieces
        (using endpoint_values) and verifying they agree to machine precision.
        """
        f = chebfun(jnp.cos, domain=[-1, 0, 1])
        F = f.cumsum()
        # Right endpoint of piece 0 and left endpoint of piece 1 should match
        p0 = F.funs[0]
        p1 = F.funs[1]
        _, rval = p0.endpoint_values
        lval, _ = p1.endpoint_values
        npt.assert_allclose(rval, lval, atol=1e-13)

    def test_cumsum_multipiece_left_endpoint_zero(self):
        """Piecewise cumsum: F(a) = 0 at the global left endpoint."""
        f = chebfun(jnp.sin, domain=[-1, 0, 1])
        F = f.cumsum()
        val = float(F(jnp.float64(-1.0)))
        npt.assert_allclose(val, 0.0, atol=1e-13)


# ============================================================================
# Tier 4: Calculus — sum (definite integral)
# ============================================================================


class TestChebfunSum:
    """Tests for Chebfun.sum().

    JAX contract: jit=yes.
    """

    def test_sin_integral_on_symmetric_domain(self):
        """int_{-1}^{1} sin(x) dx == 0 (odd function)."""
        f = chebfun(jnp.sin)
        result = float(f.sum())
        npt.assert_allclose(result, 0.0, atol=1e-13)

    def test_cos_integral(self):
        """int_{-1}^{1} cos(x) dx == 2*sin(1)."""
        f = chebfun(jnp.cos)
        expected = 2.0 * float(jnp.sin(jnp.float64(1.0)))
        result = float(f.sum())
        npt.assert_allclose(result, expected, rtol=1e-12)

    def test_exp_integral(self):
        """int_{-1}^{1} exp(x) dx == e - 1/e."""
        f = chebfun(jnp.exp)
        expected = float(jnp.exp(jnp.float64(1.0))) - float(jnp.exp(jnp.float64(-1.0)))
        result = float(f.sum())
        npt.assert_allclose(result, expected, rtol=1e-12)

    def test_sin_sq_integral(self):
        """int_{-1}^{1} sin^2(x) dx = 1 - sin(2)/2  (= 1 - sin(1)*cos(1))."""
        f = chebfun(jnp.sin)
        h = f * f
        result = float(h.sum())
        expected = float(1.0 - jnp.sin(jnp.float64(2.0)) / 2.0)
        npt.assert_allclose(result, expected, rtol=1e-12)

    def test_constant_integral(self):
        """int_{-1}^{1} 3 dx == 6."""
        f = chebfun(3.0)
        result = float(f.sum())
        npt.assert_allclose(result, 6.0, rtol=1e-13)

    def test_sum_custom_domain(self):
        """int_{0}^{pi} sin(x) dx == 2."""
        f = chebfun(jnp.sin, domain=[0, jnp.pi])
        result = float(f.sum())
        npt.assert_allclose(result, 2.0, rtol=1e-12)

    def test_sum_multipiece(self):
        """Piecewise integral == sum of piece integrals."""
        f_one = chebfun(jnp.exp)
        f_two = chebfun(jnp.exp, domain=[-1, 0, 1])
        npt.assert_allclose(
            float(f_one.sum()), float(f_two.sum()), rtol=1e-12
        )

    def test_sum_jit(self):
        """sum() is JIT-safe."""
        f = chebfun(jnp.cos)
        jit_sum = jax.jit(lambda: f.sum())
        result = float(jit_sum())
        expected = 2.0 * float(jnp.sin(jnp.float64(1.0)))
        npt.assert_allclose(result, expected, rtol=1e-12)


# ============================================================================
# Tier 5: Calculus — inner product and norm
# ============================================================================


class TestChebfunInnerNorm:
    """Tests for Chebfun.inner() and Chebfun.norm().

    JAX contract: jit=yes.
    """

    def test_inner_sin_sin(self):
        """<sin, sin> == int_{-1}^{1} sin^2(x) dx."""
        f = chebfun(jnp.sin)
        result = float(f.inner(f))
        expected = float((f * f).sum())
        npt.assert_allclose(result, expected, rtol=1e-12)

    def test_inner_sin_cos_is_zero(self):
        r"""<sin, cos> = int_{-1}^{1} sin(x)cos(x) dx = 0.

        By symmetry: sin(x)*cos(x) = sin(2x)/2, which is an odd function,
        so its integral over a symmetric domain is 0.
        """
        f = chebfun(jnp.sin)
        g = chebfun(jnp.cos)
        result = float(f.inner(g))
        npt.assert_allclose(result, 0.0, atol=1e-13)

    def test_inner_domain_mismatch_raises(self):
        """inner() with different domains should raise ValueError."""
        f = chebfun(jnp.sin)
        g = chebfun(jnp.sin, domain=[0, 1])
        with pytest.raises(ValueError, match="domains do not match"):
            f.inner(g)

    def test_norm2_sin(self):
        """||sin||_2^2 == <sin, sin> == integral of sin^2."""
        f = chebfun(jnp.sin)
        n = float(f.norm(2))
        expected = float(jnp.sqrt(f.inner(f)))
        npt.assert_allclose(n, expected, rtol=1e-12)

    def test_norm2_positive(self):
        """L2 norm is positive."""
        f = chebfun(jnp.sin)
        assert float(f.norm()) > 0

    def test_norm_inf(self):
        """L-inf norm of sin is max|sin| ~ 0.8415."""
        f = chebfun(jnp.sin)
        n_inf = float(f.norm(jnp.inf))
        # max of |sin| on [-1, 1] is sin(1)
        expected = float(jnp.sin(jnp.float64(1.0)))
        npt.assert_allclose(n_inf, expected, rtol=1e-3)

    def test_norm_custom_domain(self):
        """||sin||_2 on [0, pi]."""
        f = chebfun(jnp.sin, domain=[0, jnp.pi])
        n = float(f.norm())
        # int_0^pi sin^2 dx = pi/2
        expected = float(jnp.sqrt(jnp.pi / 2.0))
        npt.assert_allclose(n, expected, rtol=1e-10)


# ============================================================================
# Tier 6: Calculus — mean
# ============================================================================


class TestChebfunMean:
    """Tests for Chebfun.mean()."""

    def test_mean_constant(self):
        """mean(c) == c for any constant."""
        f = chebfun(3.0)
        result = float(f.mean())
        npt.assert_allclose(result, 3.0, rtol=1e-13)

    def test_mean_sin(self):
        """mean(sin) on [-1, 1] is 0 (odd function)."""
        f = chebfun(jnp.sin)
        result = float(f.mean())
        npt.assert_allclose(result, 0.0, atol=1e-13)

    def test_mean_cos_on_pi(self):
        """mean(sin) on [0, pi] = 2/pi (the classic result)."""
        f = chebfun(jnp.sin, domain=[0, jnp.pi])
        result = float(f.mean())
        expected = 2.0 / float(jnp.pi)
        npt.assert_allclose(result, expected, rtol=1e-11)


# ============================================================================
# Tier 7: Rootfinding
# ============================================================================


class TestChebfunRoots:
    """Tests for Chebfun.roots().

    JAX contract: jit=NO (variable output size).
    """

    def test_sin_root_at_zero(self):
        """sin has a root at 0 on [-1, 1]."""
        f = chebfun(jnp.sin)
        r = np.array(f.roots())
        npt.assert_allclose(r, [0.0], atol=1e-12)

    def test_sin_roots_on_minus_pi_to_pi(self):
        """sin has roots at -pi, 0, pi on [-pi, pi]."""
        f = chebfun(jnp.sin, domain=[-jnp.pi, jnp.pi])
        r = np.array(f.roots())
        expected = np.array([-float(jnp.pi), 0.0, float(jnp.pi)])
        npt.assert_allclose(r, expected, atol=1e-10)

    def test_cos_roots_on_minus_pi_to_pi(self):
        """cos has roots at -pi/2 and pi/2 on [-pi, pi]."""
        f = chebfun(jnp.cos, domain=[-jnp.pi, jnp.pi])
        r = np.array(f.roots())
        expected = np.sort([-float(jnp.pi / 2), float(jnp.pi / 2)])
        assert len(r) == 2
        npt.assert_allclose(r, expected, atol=1e-10)

    def test_poly_roots(self):
        """x^2 - 0.25 has roots at ±0.5."""
        x_id = Chebfun.identity()
        h = x_id ** 2 - 0.25
        r = np.array(h.roots())
        npt.assert_allclose(np.sort(r), [-0.5, 0.5], atol=1e-12)

    def test_no_roots_in_domain(self):
        """exp(x) > 0, so no roots."""
        f = chebfun(jnp.exp)
        r = np.array(f.roots())
        assert r.shape[0] == 0, f"Expected 0 roots, got {r}"

    def test_roots_multipiece(self):
        """Roots from a two-piece Chebfun are collected and deduplicated.

        sin on [-pi, 0, pi] (two pieces) has roots at -pi, 0, pi.
        The root at 0 is a breakpoint shared between the two pieces;
        it should appear only once in the output.
        """
        f = chebfun(jnp.sin, domain=[-jnp.pi, 0, jnp.pi])
        r = np.array(f.roots())
        expected = np.array([-float(jnp.pi), 0.0, float(jnp.pi)])
        assert len(r) == 3, f"Expected 3 roots (no duplicates), got {len(r)}: {r}"
        npt.assert_allclose(r, expected, atol=1e-10)


# ============================================================================
# Tier 8: Extrema
# ============================================================================


class TestChebfunExtrema:
    """Tests for Chebfun.max(), Chebfun.min(), Chebfun.minandmax().

    JAX contract: jit=NO (uses roots of derivative).
    """

    def test_max_of_sin_on_zero_pi(self):
        """max of sin on [0, pi] is 1 at x = pi/2."""
        f = chebfun(jnp.sin, domain=[0, jnp.pi])
        x_max, f_max = f.max()
        npt.assert_allclose(f_max, 1.0, atol=1e-10)
        npt.assert_allclose(x_max, float(jnp.pi / 2), atol=1e-9)

    def test_min_of_cos_on_zero_pi(self):
        """min of cos on [0, pi] is -1 at x = pi."""
        f = chebfun(jnp.cos, domain=[0, jnp.pi])
        x_min, f_min = f.min()
        npt.assert_allclose(f_min, -1.0, atol=1e-10)
        npt.assert_allclose(x_min, float(jnp.pi), atol=1e-9)

    def test_minandmax_sin(self):
        """minandmax of sin on [-1, 1] gives -sin(1) and sin(1)."""
        f = chebfun(jnp.sin)
        (x_min, f_min), (x_max, f_max) = f.minandmax()
        sin1 = float(jnp.sin(jnp.float64(1.0)))
        npt.assert_allclose(f_min, -sin1, atol=1e-10)
        npt.assert_allclose(f_max, sin1, atol=1e-10)

    def test_min_max_consistency(self):
        """min and max should be consistent with minandmax."""
        f = chebfun(jnp.cos, domain=[0, jnp.pi])
        (x_min, f_min), (x_max, f_max) = f.minandmax()
        x_min2, f_min2 = f.min()
        x_max2, f_max2 = f.max()
        npt.assert_allclose(f_min, f_min2, atol=1e-14)
        npt.assert_allclose(f_max, f_max2, atol=1e-14)


# ============================================================================
# Tier 9: Composed operations (integration tests)
# ============================================================================


class TestChebfunComposed:
    """Composed operation integration tests."""

    def test_sin_sq_norm(self):
        """||sin||_2^2 = int sin^2 dx = 1 - sin(2)/2."""
        f = chebfun(jnp.sin)
        n_sq = float(f.norm() ** 2)
        expected = float(1.0 - jnp.sin(jnp.float64(2.0)) / 2.0)
        npt.assert_allclose(n_sq, expected, rtol=1e-11)

    def test_fundamental_theorem_of_calculus(self):
        """int_a^b f'(x) dx = f(b) - f(a)."""
        f = chebfun(jnp.exp)
        fp = f.diff()
        integral = float(fp.sum())
        expected = float(jnp.exp(jnp.float64(1.0))) - float(jnp.exp(jnp.float64(-1.0)))
        npt.assert_allclose(integral, expected, rtol=1e-12)

    def test_sin_plus_cos_sum(self):
        """int_{-1}^{1} (sin + cos)(x) dx = 2*sin(1)."""
        f = chebfun(jnp.sin)
        g = chebfun(jnp.cos)
        h = f + g
        result = float(h.sum())
        expected = float(2.0 * jnp.sin(jnp.float64(1.0)))
        npt.assert_allclose(result, expected, rtol=1e-12)

    def test_diff_sin_roots(self):
        """Roots of d(sin^2)/dx = 2*sin*cos = sin(2x) on [-1,1] are {-pi/4?, 0, pi/4?}.

        sin^2 has extrema where 2*sin(x)*cos(x)=0 i.e. x=0, ±1.
        On [-1, 1] these are x=-1, 0, 1.
        """
        f = chebfun(jnp.sin)
        g = f * f  # sin^2
        gp = g.diff()  # 2*sin*cos = sin(2x)
        r = np.array(gp.roots())
        # Roots of sin(2x) in [-1, 1] are 0 (and endpoints ±1 approximately)
        # 2x = 0 => x=0, ±pi/2 ~ ±1.5708 (outside [-1,1])
        assert r.shape[0] >= 1
        npt.assert_allclose(np.sort(r)[len(r) // 2], 0.0, atol=1e-10)

    def test_chebfun_from_arithmetic_is_correct_callable(self):
        """The result of arithmetic is a proper Chebfun (not just coefficients)."""
        f = chebfun(jnp.sin)
        g = chebfun(jnp.cos)
        h = f + g
        assert isinstance(h, Chebfun)
        assert h.ishappy


# ============================================================================
# Tier 10: MATLAB golden references (if available)
# ============================================================================


@pytest.mark.matlab
class TestMATLABGoldenOps:
    """Comparison against MATLAB Chebfun operation golden references.

    Requires tests/references/chebfun_ops.mat. These are generated by
    matlab_harness/generate_refs_ops.m and committed to the repo.

    Skip this class if the reference file is not present.
    """

    @pytest.fixture(autouse=True)
    def load_refs(self, request):
        """Load MATLAB references, skip if not available."""
        from pathlib import Path

        import scipy.io

        ref_path = Path(__file__).parent.parent / "references" / "chebfun_ops.mat"
        if not ref_path.exists():
            pytest.skip(
                f"MATLAB golden ref chebfun_ops.mat not found at {ref_path}. "
                f"Generate with matlab_harness/generate_refs_ops.m."
            )
        data = scipy.io.loadmat(str(ref_path), squeeze_me=True)
        self.refs = {k: v for k, v in data.items() if not k.startswith("__")}

    def test_sin_integral_vs_matlab(self):
        """int_{-1}^{1} sin(x) dx should match MATLAB."""
        f = chebfun(jnp.sin)
        result = float(f.sum())
        expected = float(self.refs["sin_integral"])
        npt.assert_allclose(result, expected, rtol=1e-12)

    def test_cos_integral_vs_matlab(self):
        """int_{-1}^{1} cos(x) dx should match MATLAB."""
        f = chebfun(jnp.cos)
        result = float(f.sum())
        expected = float(self.refs["cos_integral"])
        npt.assert_allclose(result, expected, rtol=1e-12)

    def test_sin_diff_coeffs_vs_matlab(self):
        """Coefficients of diff(sin) should match MATLAB."""
        f = chebfun(jnp.sin)
        fp = f.diff()
        mat_coeffs = np.asarray(self.refs["sin_diff_coeffs"])
        our_coeffs = np.array(fp.coeffs)
        n = min(len(our_coeffs), len(mat_coeffs))
        npt.assert_allclose(our_coeffs[:n], mat_coeffs[:n], rtol=1e-12, atol=1e-14)

    def test_sin_roots_vs_matlab(self):
        """Roots of sin on [-1, 1] should match MATLAB."""
        f = chebfun(jnp.sin)
        r = np.array(f.roots())
        expected = np.asarray(self.refs["sin_roots"])
        npt.assert_allclose(r, expected, atol=1e-12)

    def test_sin_norm_vs_matlab(self):
        """L2 norm of sin should match MATLAB."""
        f = chebfun(jnp.sin)
        result = float(f.norm())
        expected = float(self.refs["sin_norm2"])
        npt.assert_allclose(result, expected, rtol=1e-12)
