"""Tests for chebfunjax.chebfun1d.chebfun — Chebfun class and factory.

JAX contract
------------
- f(x)             jit=yes (single-piece), vmap=yes, grad=yes
- f(x)             jit=NO  (multi-piece, Python dispatch)
- chebfun(func)    jit=NO  (adaptive construction, Python loop)

MATLAB golden refs: tests/references/chebfun.mat  (generated by
matlab_harness/generate_refs.m once MATLAB is available).
"""

from __future__ import annotations

import functools

import jax
import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest

import chebfunjax as cj
from chebfunjax.chebfun1d.chebfun import Chebfun, _Piece, chebfun
from chebfunjax.domain import Domain

# Tolerances from project.conf
RTOL = 1e-12
ATOL = 1e-14


# ============================================================================
# Tier 1: Construction — mathematical correctness
# ============================================================================


class TestChebfunConstruction:
    """Tests for the chebfun() factory and Chebfun construction methods.

    JAX contract: jit=NO (adaptive construction uses Python loop).
    """

    def test_sin_default_domain(self):
        """f = chebfun(jnp.sin) on [-1, 1] should give 14 coefficients."""
        f = chebfun(jnp.sin)
        assert f.ishappy
        assert len(f) == 14, f"Expected 14 coefficients for sin on [-1,1], got {len(f)}"

    def test_sin_custom_domain(self):
        """f = chebfun(jnp.sin, domain=[0, jnp.pi]) should work."""
        f = chebfun(jnp.sin, domain=[0, jnp.pi])
        assert f.ishappy
        assert len(f) > 0
        # The domain should be recorded
        assert abs(f.domain.a - 0.0) < 1e-14
        assert abs(f.domain.b - float(jnp.pi)) < 1e-12

    def test_exp_adaptive(self):
        """chebfun(jnp.exp) should converge adaptively."""
        f = chebfun(jnp.exp)
        assert f.ishappy

    def test_constant_scalar(self):
        """chebfun(3.14) should give a constant function."""
        f = chebfun(3.14)
        assert f.ishappy
        x = jnp.linspace(-1.0, 1.0, 20, dtype=jnp.float64)
        npt.assert_allclose(np.array(f(x)), 3.14, atol=1e-14)

    def test_fixed_n(self):
        """chebfun(jnp.sin, n=20) should give exactly 20 coefficients."""
        f = chebfun(jnp.sin, n=20)
        assert len(f) == 20

    def test_from_coeffs_roundtrip(self):
        """Chebfun.from_coeffs should store and return the given coefficients."""
        c = jnp.array([1.0, 0.5, -0.25, 0.1], dtype=jnp.float64)
        f = Chebfun.from_coeffs(c)
        npt.assert_allclose(np.array(f.coeffs), np.array(c), atol=1e-15)

    def test_from_coeffs_default_domain(self):
        """from_coeffs with no domain defaults to [-1, 1]."""
        c = jnp.array([1.0, 0.0, -0.5], dtype=jnp.float64)
        f = Chebfun.from_coeffs(c)
        assert f.domain == Domain((-1.0, 1.0))

    def test_from_values_roundtrip(self):
        """from_values -> coeffs -> values should match."""
        from chebfunjax.utils.quadrature import chebpts
        n = 10
        x = chebpts(n)
        v = jnp.sin(x)
        f = Chebfun.from_values(v)
        npt.assert_allclose(np.array(f.values), np.array(v), atol=1e-14)

    def test_from_coeffs_custom_domain(self):
        """from_coeffs on [0, 2] should work."""
        c = jnp.array([1.0, 0.5], dtype=jnp.float64)
        dom = Domain((0.0, 2.0))
        f = Chebfun.from_coeffs(c, domain=dom)
        assert f.domain == dom

    def test_identity(self):
        """Chebfun.identity() should give f(x) = x on [-1, 1]."""
        x_id = Chebfun.identity()
        xs = jnp.array([-1.0, -0.5, 0.0, 0.5, 1.0], dtype=jnp.float64)
        npt.assert_allclose(np.array(x_id(xs)), np.array(xs), atol=1e-14)

    def test_identity_custom_domain(self):
        """Chebfun.identity(Domain((0, 2))) should give f(x) = x on [0, 2]."""
        dom = Domain((0.0, 2.0))
        x_id = Chebfun.identity(dom)
        xs = jnp.array([0.0, 0.5, 1.0, 1.5, 2.0], dtype=jnp.float64)
        npt.assert_allclose(np.array(x_id(xs)), np.array(xs), atol=1e-13)

    def test_invalid_f_type(self):
        """chebfun with non-callable, non-scalar should raise TypeError."""
        with pytest.raises(TypeError, match="Cannot construct"):
            chebfun([1, 2, 3])

    def test_invalid_domain(self):
        """chebfun with a degenerate domain should raise ValueError."""
        with pytest.raises(ValueError):
            chebfun(jnp.sin, domain=(1.0, 1.0))

    def test_f_none_raises(self):
        """chebfun(None) should raise ValueError."""
        with pytest.raises(ValueError, match="f=None"):
            chebfun(None)

    def test_multipiece_domain(self):
        """chebfun on a piecewise domain produces multiple pieces."""
        f = chebfun(jnp.sin, domain=[-1, 0, 1])
        assert len(f.funs) == 2


# ============================================================================
# Tier 2: Evaluation
# ============================================================================


class TestChebfunEvaluation:
    """Tests for Chebfun.__call__ evaluation.

    JAX contract: jit=yes (single-piece), vmap=yes, grad=yes.
    """

    def test_sin_at_point(self):
        """sin(0.5) at machine precision."""
        f = chebfun(jnp.sin)
        y = float(f(jnp.float64(0.5)))
        expected = float(jnp.sin(jnp.float64(0.5)))
        npt.assert_allclose(y, expected, rtol=RTOL, atol=ATOL)

    def test_sin_at_array(self):
        """sin at 50 points should match jnp.sin at rtol=1e-12."""
        f = chebfun(jnp.sin)
        xs = jnp.linspace(-1.0, 1.0, 50, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(f(xs)), np.array(jnp.sin(xs)), rtol=RTOL, atol=ATOL
        )

    def test_sin_endpoints(self):
        """Evaluate at domain endpoints."""
        f = chebfun(jnp.sin)
        npt.assert_allclose(
            float(f(jnp.float64(-1.0))), float(jnp.sin(jnp.float64(-1.0))), rtol=1e-12
        )
        npt.assert_allclose(
            float(f(jnp.float64(1.0))), float(jnp.sin(jnp.float64(1.0))), rtol=1e-12
        )

    def test_custom_domain_eval(self):
        """chebfun(jnp.sin, domain=[0, pi]) evaluated at pi/2 should be 1."""
        f = chebfun(jnp.sin, domain=[0, jnp.pi])
        y = float(f(jnp.float64(jnp.pi / 2)))
        npt.assert_allclose(y, 1.0, atol=1e-12)

    def test_custom_domain_multiple_points(self):
        """chebfun on [0, pi] vs jnp.sin at 30 points."""
        f = chebfun(jnp.sin, domain=[0, jnp.pi])
        xs = jnp.linspace(0.0, float(jnp.pi), 30, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(f(xs)), np.array(jnp.sin(xs)), atol=1e-12
        )

    def test_exp_eval(self):
        """exp Chebfun at several points."""
        f = chebfun(jnp.exp)
        xs = jnp.array([-0.7, -0.3, 0.0, 0.3, 0.7], dtype=jnp.float64)
        npt.assert_allclose(
            np.array(f(xs)), np.array(jnp.exp(xs)), rtol=1e-13
        )

    def test_scalar_input(self):
        """Scalar input (0-d array) should return scalar."""
        f = chebfun(jnp.sin)
        x = jnp.float64(0.5)
        y = f(x)
        assert y.ndim == 0

    def test_multipiece_eval(self):
        """Two-piece Chebfun should evaluate correctly across the join."""
        f = chebfun(jnp.sin, domain=[-1, 0, 1])
        xs = jnp.linspace(-1.0, 1.0, 50, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(f(xs)), np.array(jnp.sin(xs)), atol=1e-12
        )

    # ------------------------------------------------------------------
    # JAX contract tests
    # ------------------------------------------------------------------

    def test_jit(self):
        """Single-piece evaluation is JIT-safe via eqx.filter_jit.

        Note: the correct equinox pattern is ``eqx.filter_jit(f)`` rather than
        bare ``jax.jit(f)``, because the latter tries to hash the JAX arrays
        stored in the module (which are dynamic leaves, not static).
        See docs/jax-contract.md.
        """
        import equinox as eqx
        f = chebfun(jnp.sin)
        jit_f = eqx.filter_jit(f)
        xs = jnp.linspace(-1.0, 1.0, 20, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(jit_f(xs)), np.array(jnp.sin(xs)), rtol=1e-12
        )

    def test_jit_via_lambda(self):
        """jax.jit(lambda x: f(x)) is also JIT-safe for single-piece."""
        f = chebfun(jnp.sin)
        jit_f = jax.jit(lambda x: f(x))
        xs = jnp.linspace(-1.0, 1.0, 20, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(jit_f(xs)), np.array(jnp.sin(xs)), rtol=1e-12
        )

    def test_vmap(self):
        """Single-piece evaluation is vmap-safe via jax.vmap(lambda x: f(x))."""
        f = chebfun(jnp.sin)
        vmapped = jax.vmap(lambda x: f(jnp.atleast_1d(x))[0])
        xs = jnp.linspace(-1.0, 1.0, 20, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(vmapped(xs)), np.array(jnp.sin(xs)), rtol=1e-12
        )

    def test_grad(self):
        """d/dx [f(x)] at x=0.5 should match jnp.cos(0.5) approximately."""
        f = chebfun(jnp.sin)
        grad_f = jax.grad(lambda x: f(jnp.atleast_1d(x))[0])
        dfdx = float(grad_f(jnp.float64(0.5)))
        expected = float(jnp.cos(jnp.float64(0.5)))
        # Gradient through Clenshaw should match cos to at least 1e-10
        npt.assert_allclose(dfdx, expected, rtol=1e-10)

    def test_jit_custom_domain(self):
        """JIT on a Chebfun with a non-standard domain (via eqx.filter_jit)."""
        import equinox as eqx
        f = chebfun(jnp.sin, domain=[0.0, jnp.pi])
        jit_f = eqx.filter_jit(f)
        xs = jnp.linspace(0.0, float(jnp.pi), 20, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(jit_f(xs)), np.array(jnp.sin(xs)), atol=1e-12
        )


# ============================================================================
# Tier 3: Properties
# ============================================================================


class TestChebfunProperties:
    """Tests for Chebfun properties: domain, coeffs, values, vscale, ishappy."""

    def test_len_sin(self):
        """len(f) == 14 for sin on [-1, 1]."""
        f = chebfun(jnp.sin)
        assert len(f) == 14

    def test_domain_default(self):
        """Default domain is [-1, 1]."""
        f = chebfun(jnp.sin)
        assert f.domain == Domain((-1.0, 1.0))

    def test_domain_custom(self):
        """Custom domain is stored correctly."""
        f = chebfun(jnp.sin, domain=[0, jnp.pi])
        assert abs(f.domain.a - 0.0) < 1e-14
        assert abs(f.domain.b - float(jnp.pi)) < 1e-12

    def test_vscale_sin(self):
        """vscale of sin should be close to 1 (max |sin| on [-1,1])."""
        f = chebfun(jnp.sin)
        vs = f.vscale
        # |sin(x)| <= 1 on [-1,1], max at x=1: sin(1) ~ 0.8415
        npt.assert_allclose(vs, float(jnp.max(jnp.abs(jnp.sin(
            jnp.linspace(-1.0, 1.0, 1000, dtype=jnp.float64)
        )))), rtol=1e-3)

    def test_ishappy_sin(self):
        """sin on [-1, 1] should be happy (converged)."""
        f = chebfun(jnp.sin)
        assert f.ishappy

    def test_coeffs_length(self):
        """coeffs array length matches len(f)."""
        f = chebfun(jnp.sin)
        assert f.coeffs.shape[0] == len(f)

    def test_values_length(self):
        """values array length matches len(f) for single-piece."""
        f = chebfun(jnp.sin)
        assert f.values.shape[0] == len(f)

    def test_values_consistent_with_coeffs(self):
        """values should be recoverable from coeffs via coeffs2vals."""
        from chebfunjax.utils.transforms import coeffs2vals
        f = chebfun(jnp.sin)
        v_from_coeffs = coeffs2vals(f.coeffs)
        npt.assert_allclose(
            np.array(f.values), np.array(v_from_coeffs), atol=1e-14
        )


# ============================================================================
# Tier 4: repr / str
# ============================================================================


class TestChebfunRepr:
    """Tests for Chebfun.__repr__ and __str__."""

    def test_repr_contains_header(self):
        """repr should start with 'Chebfun column'."""
        f = chebfun(jnp.sin)
        r = repr(f)
        assert r.startswith("Chebfun column")

    def test_repr_contains_interval(self):
        """repr should mention the interval."""
        f = chebfun(jnp.sin)
        r = repr(f)
        assert "-1" in r and "1" in r

    def test_repr_contains_vscale(self):
        """repr should include 'vscale'."""
        f = chebfun(jnp.sin)
        r = repr(f)
        assert "vscale" in r

    def test_repr_single_piece_label(self):
        """Single-piece repr should say '1 smooth piece'."""
        f = chebfun(jnp.sin)
        r = repr(f)
        assert "1 smooth piece" in r

    def test_repr_two_pieces(self):
        """Two-piece repr should say '2 smooth pieces'."""
        f = chebfun(jnp.sin, domain=[-1, 0, 1])
        r = repr(f)
        assert "2 smooth pieces" in r
        assert "total length" in r

    def test_str_format(self):
        """str(f) should be one line matching the spec."""
        f = chebfun(jnp.sin)
        s = str(f)
        assert s.startswith("<Chebfun")
        assert "length" in s
        assert "\n" not in s


# ============================================================================
# Tier 5: restrict
# ============================================================================


class TestChebfunRestrict:
    """Tests for Chebfun.restrict."""

    def test_restrict_half_interval(self):
        """Restricting sin to [0, 1] should give correct values."""
        f = chebfun(jnp.sin)
        g = f.restrict(0.0, 1.0)
        xs = jnp.linspace(0.0, 1.0, 20, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(g(xs)), np.array(jnp.sin(xs)), atol=1e-12
        )

    def test_restrict_domain_recorded(self):
        """Restricted Chebfun should have the new domain."""
        f = chebfun(jnp.sin)
        g = f.restrict(0.0, 1.0)
        assert abs(g.domain.a - 0.0) < 1e-14
        assert abs(g.domain.b - 1.0) < 1e-14

    def test_restrict_full_interval(self):
        """Restricting to the full domain should return a copy."""
        f = chebfun(jnp.sin)
        g = f.restrict(-1.0, 1.0)
        xs = jnp.linspace(-1.0, 1.0, 20, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(g(xs)), np.array(f(xs)), atol=1e-14
        )

    def test_restrict_outside_raises(self):
        """Restricting outside the domain should raise ValueError."""
        f = chebfun(jnp.sin)
        with pytest.raises(ValueError, match="sub-interval"):
            f.restrict(-2.0, 1.0)


# ============================================================================
# Tier 6: top-level API exports
# ============================================================================


class TestTopLevelAPI:
    """Tests that cj.chebfun is accessible and works from the package root."""

    def test_cj_chebfun_is_accessible(self):
        """cj.chebfun should be importable and callable."""
        f = cj.chebfun(jnp.sin)
        assert isinstance(f, Chebfun)

    def test_cj_Chebfun_is_accessible(self):
        """cj.Chebfun should be importable."""
        assert cj.Chebfun is Chebfun

    def test_from_coeffs_on_callable(self):
        """chebfun.from_coeffs should work."""
        c = jnp.array([1.0, 0.5, -0.25], dtype=jnp.float64)
        f = cj.chebfun.from_coeffs(c)
        assert isinstance(f, Chebfun)
        npt.assert_allclose(np.array(f.coeffs), np.array(c), atol=1e-15)

    def test_from_values_on_callable(self):
        """chebfun.from_values should work."""
        from chebfunjax.utils.quadrature import chebpts
        n = 8
        x = chebpts(n)
        v = jnp.exp(x)
        f = cj.chebfun.from_values(v)
        assert isinstance(f, Chebfun)

    def test_identity_on_callable(self):
        """chebfun.identity() should work."""
        x_id = cj.chebfun.identity()
        assert isinstance(x_id, Chebfun)


# ============================================================================
# Tier 7: MATLAB golden references (if available)
# ============================================================================


@pytest.mark.matlab
class TestMATLABGolden:
    """Comparison against MATLAB Chebfun golden references.

    Requires tests/references/chebfun.mat. These are generated by
    matlab_harness/generate_refs.m and committed to the repo.

    Skip this class if the reference file is not present.

    JAX contract: not applicable (offline comparison).
    """

    @pytest.fixture(autouse=True)
    def load_refs(self, request):
        """Load MATLAB references, skip if not available."""
        from pathlib import Path
        import scipy.io

        ref_path = Path(__file__).parent.parent / "references" / "chebfun.mat"
        if not ref_path.exists():
            pytest.skip(
                f"MATLAB golden ref chebfun.mat not found at {ref_path}. "
                f"Generate with matlab_harness/generate_refs.m."
            )
        data = scipy.io.loadmat(str(ref_path), squeeze_me=True)
        self.refs = {k: v for k, v in data.items() if not k.startswith("__")}

    def test_sin_coeffs_vs_matlab(self):
        """sin coefficients should match MATLAB's chebfun(sin)."""
        f = chebfun(jnp.sin)
        mat_coeffs = self.refs["sin_coeffs"]
        npt.assert_allclose(
            np.array(f.coeffs),
            np.asarray(mat_coeffs),
            rtol=1e-12,
            atol=1e-14,
        )

    def test_sin_n_vs_matlab(self):
        """Number of coefficients for sin should match MATLAB."""
        f = chebfun(jnp.sin)
        mat_n = int(self.refs["sin_n"])
        assert len(f) == mat_n

    def test_exp_n_vs_matlab(self):
        """Number of coefficients for exp should match MATLAB."""
        f = chebfun(jnp.exp)
        mat_n = int(self.refs["exp_n"])
        assert len(f) == mat_n

    def test_eval_vs_matlab(self):
        """Evaluation at MATLAB test points should match MATLAB values."""
        f = chebfun(jnp.sin)
        xs = jnp.asarray(self.refs["eval_pts"], dtype=jnp.float64)
        expected = np.asarray(self.refs["sin_eval_vals"])
        npt.assert_allclose(
            np.array(f(xs)), expected, rtol=1e-12, atol=1e-14
        )
