"""Tests for special functions applied to Chebfun objects (U44).

All functions are thin wrappers around ``_apply_fun`` which calls
``_Piece.from_function`` adaptively.  Tests verify:

1. Method form:  ``f.sin()`` etc.
2. Module form:  ``cj.sin(f)`` etc.
3. Mathematical round-trips:  ``exp(log(f)) ≈ f``, ``sin^2 + cos^2 ≈ 1``, etc.
4. sin(identity) matches chebfun(sin) directly.
5. abs / sign introduce breakpoints at zeros correctly.
6. Multi-piece Chebfuns are handled piece-by-piece.

JAX contract
------------
- All special functions: NOT JIT-safe (adaptive construction).
- The *result* Chebfun evaluation is JIT/vmap-safe (single-piece case).

MATLAB golden refs: tests/references/chebfun_specfun.mat (generated by
matlab_harness/generate_refs_specfun.m once MATLAB is available).
"""

from __future__ import annotations

import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest

import chebfunjax as cj
from chebfunjax.chebfun1d.chebfun import Chebfun, chebfun

# Standard tolerances for spectral accuracy (float64).
# Special-function compositions tolerate slightly more error than
# raw polynomial arithmetic because each adaptive build adds ~eps rounding.
RTOL = 1e-12
ATOL = 1e-12

# Looser tolerance for near-singular functions (arcsin/arccos near ±1,
# log near 0, sqrt near 0) where the adaptive algorithm may need more
# coefficients to resolve the boundary singularity.
ATOL_LOOSE = 1e-10


# ============================================================================
# Helpers
# ============================================================================


def _pts(n=40, a=-1.0, b=1.0):
    """Uniformly spaced test points in (a, b), avoiding endpoints."""
    return jnp.linspace(a + 1e-8, b - 1e-8, n, dtype=jnp.float64)


# ============================================================================
# Tier 1: sin, cos — basic transcendentals
# ============================================================================


class TestSinCos:
    """sin and cos: method form, module form, and identities."""

    def test_sin_identity(self):
        """sin(identity) == chebfun(sin) pointwise."""
        x = Chebfun.identity()
        f = x.sin()
        g = chebfun(jnp.sin)
        xs = _pts()
        npt.assert_allclose(
            np.array(f(xs)), np.array(g(xs)), rtol=RTOL, atol=ATOL,
            err_msg="sin(identity) must equal chebfun(jnp.sin)"
        )

    def test_cos_identity(self):
        """cos(identity) == chebfun(cos) pointwise."""
        x = Chebfun.identity()
        f = x.cos()
        g = chebfun(jnp.cos)
        xs = _pts()
        npt.assert_allclose(
            np.array(f(xs)), np.array(g(xs)), rtol=RTOL, atol=ATOL,
            err_msg="cos(identity) must equal chebfun(jnp.cos)"
        )

    def test_module_sin(self):
        """cj.sin(f) == f.sin()."""
        f = chebfun(jnp.sin)
        g = cj.sin(f)
        h = f.sin()
        xs = _pts()
        npt.assert_allclose(
            np.array(g(xs)), np.array(h(xs)), rtol=RTOL, atol=ATOL
        )

    def test_module_cos(self):
        """cj.cos(f) == f.cos()."""
        f = chebfun(jnp.cos)
        g = cj.cos(f)
        h = f.cos()
        xs = _pts()
        npt.assert_allclose(
            np.array(g(xs)), np.array(h(xs)), rtol=RTOL, atol=ATOL
        )

    def test_pythagorean_identity(self):
        """sin(x)^2 + cos(x)^2 == 1 to spectral accuracy."""
        x = Chebfun.identity()
        s = x.sin()
        c = x.cos()
        one = s ** 2 + c ** 2
        xs = _pts()
        npt.assert_allclose(
            np.array(one(xs)),
            np.ones(len(xs)),
            rtol=RTOL,
            atol=ATOL,
            err_msg="sin^2 + cos^2 must equal 1"
        )

    def test_sin_of_cos(self):
        """sin(cos(x)) pointwise."""
        x = Chebfun.identity()
        f = x.cos().sin()
        xs = _pts()
        expected = jnp.sin(jnp.cos(xs))
        npt.assert_allclose(
            np.array(f(xs)), np.array(expected), rtol=RTOL, atol=ATOL
        )

    def test_sin_custom_domain(self):
        """sin on a custom domain [0, pi]."""
        f = chebfun(lambda x: x, domain=[0.0, float(jnp.pi)])
        s = f.sin()
        xs = jnp.linspace(0.01, float(jnp.pi) - 0.01, 30, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(s(xs)), np.array(jnp.sin(xs)), rtol=RTOL, atol=ATOL
        )


# ============================================================================
# Tier 2: exp / log round-trip
# ============================================================================


class TestExpLog:
    """exp and log: method form, module form, and round-trip."""

    def test_exp_identity(self):
        """exp(identity) == chebfun(exp) pointwise."""
        x = Chebfun.identity()
        f = x.exp()
        g = chebfun(jnp.exp)
        xs = _pts()
        npt.assert_allclose(
            np.array(f(xs)), np.array(g(xs)), rtol=RTOL, atol=ATOL
        )

    def test_log_of_exp(self):
        """log(exp(x)) == x."""
        x = Chebfun.identity()
        f = x.exp().log()
        xs = _pts()
        npt.assert_allclose(
            np.array(f(xs)), np.array(xs), rtol=RTOL, atol=ATOL,
            err_msg="log(exp(x)) must equal x"
        )

    def test_exp_of_log(self):
        """exp(log(f)) == f when f > 0."""
        # f = 2 + sin(x) is strictly positive on [-1, 1]
        f = chebfun(lambda x: 2.0 + jnp.sin(x))
        g = f.log().exp()
        xs = _pts()
        npt.assert_allclose(
            np.array(g(xs)), np.array(f(xs)), rtol=RTOL, atol=ATOL,
            err_msg="exp(log(f)) must equal f"
        )

    def test_module_exp_log(self):
        """cj.exp and cj.log match method forms."""
        f = chebfun(lambda x: 1.0 + 0.5 * x)
        g_method = f.exp().log()
        g_module = cj.log(cj.exp(f))
        xs = _pts()
        npt.assert_allclose(
            np.array(g_method(xs)), np.array(g_module(xs)), rtol=RTOL, atol=ATOL
        )

    def test_exp_sum_property(self):
        """exp(x + y) == exp(x) * exp(y) via Chebfun arithmetic."""
        x = Chebfun.identity()
        # Use x/2 and x/3 so exp doesn't blow up too much on [-1,1]
        a = (x * 0.5).exp()
        b = (x * (1.0 / 3.0)).exp()
        ab = a * b
        c = (x * (0.5 + 1.0 / 3.0)).exp()
        xs = _pts()
        npt.assert_allclose(
            np.array(ab(xs)), np.array(c(xs)), rtol=RTOL, atol=ATOL
        )


# ============================================================================
# Tier 3: sqrt
# ============================================================================


class TestSqrt:
    """sqrt: method, module, and round-trip."""

    def test_sqrt_identity(self):
        """sqrt(2 + sin(x)) pointwise."""
        f = chebfun(lambda x: 2.0 + jnp.sin(x))
        g = f.sqrt()
        xs = _pts()
        npt.assert_allclose(
            np.array(g(xs)),
            np.array(jnp.sqrt(2.0 + jnp.sin(xs))),
            rtol=RTOL, atol=ATOL
        )

    def test_sqrt_squared(self):
        """sqrt(f)^2 == f when f >= 0."""
        f = chebfun(lambda x: 1.0 + x ** 2)
        g = f.sqrt() ** 2
        xs = _pts()
        npt.assert_allclose(
            np.array(g(xs)), np.array(f(xs)), rtol=RTOL, atol=ATOL,
            err_msg="sqrt(f)^2 must equal f"
        )

    def test_module_sqrt(self):
        """cj.sqrt(f) == f.sqrt()."""
        f = chebfun(lambda x: 1.0 + 0.5 * jnp.cos(x))
        npt.assert_allclose(
            np.array(cj.sqrt(f)(_pts())),
            np.array(f.sqrt()(_pts())),
            rtol=RTOL, atol=ATOL
        )


# ============================================================================
# Tier 4: abs and sign (with breakpoint insertion)
# ============================================================================


class TestAbsSign:
    """abs and sign: breakpoint insertion, positivity, round-trip."""

    def test_abs_positive_function(self):
        """abs(f) == f when f > 0 (no breakpoints needed)."""
        f = chebfun(lambda x: 2.0 + jnp.sin(x))
        g = f.abs()
        xs = _pts()
        npt.assert_allclose(
            np.array(g(xs)), np.array(f(xs)), rtol=RTOL, atol=ATOL
        )

    def test_abs_is_nonnegative(self):
        """abs(sin(x)) >= 0 everywhere."""
        f = chebfun(jnp.sin)
        g = f.abs()
        xs = _pts()
        vals = np.array(g(xs))
        assert np.all(vals >= -1e-12), f"abs values have negative: min={vals.min()}"

    def test_abs_matches_reference(self):
        """abs(sin(x)) matches jnp.abs(sin(xs)) pointwise."""
        f = chebfun(jnp.sin)
        g = f.abs()
        xs = _pts()
        npt.assert_allclose(
            np.array(g(xs)),
            np.array(jnp.abs(jnp.sin(xs))),
            rtol=RTOL, atol=ATOL
        )

    def test_module_abs(self):
        """cj.abs(f) == f.abs()."""
        f = chebfun(jnp.sin)
        npt.assert_allclose(
            np.array(cj.abs(f)(_pts())),
            np.array(f.abs()(_pts())),
            rtol=RTOL, atol=ATOL
        )

    def test_sign_values(self):
        """sign(sin(x)) is approximately +1 or -1 on sign-constant pieces.

        Each piece is an adaptive Chebyshev approximation of a step function
        (+1 or -1 constant), so the approximation is accurate to spectral
        precision well away from the breakpoint at zero.
        """
        f = chebfun(jnp.sin)
        g = f.sign()
        # In (0, 1], sin > 0 so sign should be close to +1.
        # The Chebyshev approximation of a constant converges very fast,
        # so we expect ~eps accuracy well away from the breakpoint.
        xs_pos = jnp.linspace(0.1, 0.9, 10, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(g(xs_pos)),
            np.ones(10),
            rtol=1e-4, atol=1e-4,
            err_msg="sign(sin) should be +1 on (0.1, 0.9)"
        )
        # In [-1, 0), sin < 0 so sign should be close to -1.
        xs_neg = jnp.linspace(-0.9, -0.1, 10, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(g(xs_neg)),
            -np.ones(10),
            rtol=1e-4, atol=1e-4,
            err_msg="sign(sin) should be -1 on (-0.9, -0.1)"
        )

    def test_module_sign(self):
        """cj.sign(f) == f.sign()."""
        f = chebfun(jnp.cos)
        npt.assert_allclose(
            np.array(cj.sign(f)(_pts())),
            np.array(f.sign()(_pts())),
            rtol=RTOL, atol=ATOL
        )

    def test_abs_sign_consistency(self):
        """|f| agrees with sign(f)*f when evaluated via the same function.

        ``f.sign() * f`` requires matching domains and is not directly
        supported (sign inserts breakpoints).  Instead verify the identity
        pointwise by evaluating both sides as callables.
        """
        f = chebfun(jnp.sin)
        lhs = f.abs()
        sign_f = f.sign()
        # Evaluate away from the breakpoint at zero
        xs = jnp.linspace(-0.9, -0.1, 15, dtype=jnp.float64)
        lhs_vals = np.array(lhs(xs))
        sign_vals = np.array(sign_f(xs))
        f_vals = np.array(f(xs))
        rhs_vals = sign_vals * f_vals
        npt.assert_allclose(lhs_vals, rhs_vals, rtol=1e-4, atol=1e-4)

        xs2 = jnp.linspace(0.1, 0.9, 15, dtype=jnp.float64)
        lhs_vals2 = np.array(lhs(xs2))
        sign_vals2 = np.array(sign_f(xs2))
        f_vals2 = np.array(f(xs2))
        rhs_vals2 = sign_vals2 * f_vals2
        npt.assert_allclose(lhs_vals2, rhs_vals2, rtol=1e-4, atol=1e-4)


# ============================================================================
# Tier 5: hyperbolic functions
# ============================================================================


class TestHyperbolic:
    """sinh, cosh, tanh."""

    def test_sinh_identity(self):
        """sinh(identity) == chebfun(sinh)."""
        x = Chebfun.identity()
        f = x.sinh()
        xs = _pts()
        npt.assert_allclose(
            np.array(f(xs)), np.array(jnp.sinh(xs)), rtol=RTOL, atol=ATOL
        )

    def test_cosh_identity(self):
        """cosh(identity) == chebfun(cosh)."""
        x = Chebfun.identity()
        f = x.cosh()
        xs = _pts()
        npt.assert_allclose(
            np.array(f(xs)), np.array(jnp.cosh(xs)), rtol=RTOL, atol=ATOL
        )

    def test_tanh_identity(self):
        """tanh(identity) == chebfun(tanh)."""
        x = Chebfun.identity()
        f = x.tanh()
        xs = _pts()
        npt.assert_allclose(
            np.array(f(xs)), np.array(jnp.tanh(xs)), rtol=RTOL, atol=ATOL
        )

    def test_cosh_squared_minus_sinh_squared(self):
        """cosh^2 - sinh^2 == 1 (hyperbolic identity)."""
        x = Chebfun.identity()
        one = x.cosh() ** 2 - x.sinh() ** 2
        xs = _pts()
        npt.assert_allclose(
            np.array(one(xs)),
            np.ones(len(xs)),
            rtol=RTOL,
            atol=ATOL,
            err_msg="cosh^2 - sinh^2 must equal 1"
        )

    def test_module_sinh_cosh_tanh(self):
        """cj.sinh, cj.cosh, cj.tanh match method forms."""
        f = chebfun(lambda x: 0.5 * x)
        xs = _pts()
        npt.assert_allclose(
            np.array(cj.sinh(f)(xs)), np.array(f.sinh()(xs)), rtol=RTOL, atol=ATOL
        )
        npt.assert_allclose(
            np.array(cj.cosh(f)(xs)), np.array(f.cosh()(xs)), rtol=RTOL, atol=ATOL
        )
        npt.assert_allclose(
            np.array(cj.tanh(f)(xs)), np.array(f.tanh()(xs)), rtol=RTOL, atol=ATOL
        )


# ============================================================================
# Tier 6: inverse trig
# ============================================================================


class TestInverseTrig:
    """asin, acos, atan."""

    def test_asin_roundtrip(self):
        """asin(sin(x)) == x for x in [-1, 1]."""
        # sin maps [-pi/2, pi/2] to [-1, 1]; restrict to avoid branch issues
        # Use x/2 so we stay in the invertible range of asin
        x = Chebfun.identity()
        half_x = x * 0.5
        f = half_x.sin().asin()
        xs = _pts()
        npt.assert_allclose(
            np.array(f(xs)), np.array(xs * 0.5), rtol=RTOL, atol=ATOL_LOOSE,
            err_msg="asin(sin(x/2)) must equal x/2"
        )

    def test_acos_roundtrip(self):
        """acos(cos(t)) == t for t in [0, 1] (cos is injective on [0, pi])."""
        # Build a Chebfun on [0, 1] representing the identity t -> t.
        # Then acos(cos(t)) should equal t for t in [0, 1] (values in [0, 1] ⊂ [0, pi]).
        t = chebfun(lambda x: x, domain=[0.0, 1.0])
        f = t.cos().acos()
        xs = jnp.linspace(0.05, 0.95, 20, dtype=jnp.float64)
        npt.assert_allclose(
            np.array(f(xs)), np.array(xs),
            rtol=RTOL, atol=ATOL_LOOSE,
            err_msg="acos(cos(t)) must equal t for t in [0, 1]"
        )

    def test_atan_identity(self):
        """atan(identity) == chebfun(arctan)."""
        x = Chebfun.identity()
        f = x.atan()
        xs = _pts()
        npt.assert_allclose(
            np.array(f(xs)), np.array(jnp.arctan(xs)), rtol=RTOL, atol=ATOL
        )

    def test_module_asin_acos_atan(self):
        """cj.asin, cj.acos, cj.atan match method forms."""
        # Use a function with range in (-1, 1) for asin/acos
        f = chebfun(lambda x: 0.5 * x)
        xs = _pts()
        npt.assert_allclose(
            np.array(cj.asin(f)(xs)), np.array(f.asin()(xs)), rtol=RTOL, atol=ATOL
        )
        npt.assert_allclose(
            np.array(cj.acos(f)(xs)), np.array(f.acos()(xs)), rtol=RTOL, atol=ATOL
        )
        x = Chebfun.identity()
        npt.assert_allclose(
            np.array(cj.atan(x)(xs)), np.array(x.atan()(xs)), rtol=RTOL, atol=ATOL
        )


# ============================================================================
# Tier 7: multi-piece Chebfuns
# ============================================================================


class TestMultiPiece:
    """Special functions on piecewise Chebfuns."""

    def test_sin_multipiece(self):
        """sin on a 2-piece domain [-1, 0, 1]."""
        f = chebfun(lambda x: x, domain=[-1.0, 0.0, 1.0])
        g = f.sin()
        xs = _pts()
        npt.assert_allclose(
            np.array(g(xs)), np.array(jnp.sin(xs)), rtol=RTOL, atol=ATOL
        )

    def test_exp_multipiece(self):
        """exp on a 3-piece domain [-1, -0.3, 0.4, 1]."""
        f = chebfun(lambda x: x, domain=[-1.0, -0.3, 0.4, 1.0])
        g = f.exp()
        xs = _pts()
        npt.assert_allclose(
            np.array(g(xs)), np.array(jnp.exp(xs)), rtol=RTOL, atol=ATOL
        )

    def test_abs_multipiece(self):
        """abs on a pre-split piecewise Chebfun."""
        f = chebfun(jnp.sin, domain=[-1.0, 0.0, 1.0])
        g = f.abs()
        xs = _pts()
        npt.assert_allclose(
            np.array(g(xs)),
            np.array(jnp.abs(jnp.sin(xs))),
            rtol=RTOL, atol=ATOL
        )


# ============================================================================
# Tier 8: MATLAB golden references (skip until .mat is generated)
# ============================================================================


@pytest.mark.skip(reason="MATLAB .mat reference not yet generated")
class TestMatlabGoldenRefs:
    """Compare against MATLAB Chebfun golden references.

    Generated by ``matlab_harness/generate_refs_specfun.m`` once MATLAB
    is available.  Checks spectral accuracy at the coefficient level.
    """

    def test_sin_coeffs(self):
        """sin(x) coefficients match MATLAB reference."""
        import scipy.io
        refs = scipy.io.loadmat("tests/references/chebfun_specfun.mat")
        f = Chebfun.identity().sin()
        npt.assert_allclose(
            np.array(f.coeffs),
            refs["sin_x_coeffs"].ravel(),
            rtol=1e-14,
            atol=1e-14,
        )

    def test_exp_coeffs(self):
        """exp(x) coefficients match MATLAB reference."""
        import scipy.io
        refs = scipy.io.loadmat("tests/references/chebfun_specfun.mat")
        f = Chebfun.identity().exp()
        npt.assert_allclose(
            np.array(f.coeffs),
            refs["exp_x_coeffs"].ravel(),
            rtol=1e-14,
            atol=1e-14,
        )
