"""MATLAB golden-reference parity for higher-level chebfun1d functions.

Pins the user-facing chebfun1d operations that ``chebfun_refs.m`` never
covered (it only pinned sin/exp construction + eval):

    conv, polyfit, interp1, spline, pchip,
    besselj, bessely, airy, erf, erfc,
    cumsum / diff chains, sum, norm,
    quasimatrix svd (singular values) and qr (R factor),
    ode45 / ode113 (accuracy of an IVP solve).

Values are pinned against MATLAB Chebfun at rtol 1e-12 (project Gate 3),
except two documented exceptions:

* ``polyfit`` originally strict-xfailed (Chebyshev-series truncation
  instead of MATLAB's Legendre-series L2 projection); the library bug is
  fixed and the test now pins the MATLAB values directly.
* ``ode45`` / ``ode113`` wrap scipy ``solve_ivp`` with adaptive step
  control (rtol 1e-6), so their output is an *approximation* of the exact
  solution, not a 1e-12 identity.  The reference is the analytic solution
  and the test checks solver accuracy (rtol 1e-5) — a Gate-3
  implementation-dependent metric, documented rather than pinned at 1e-12.

Golden ref generated by matlab_harness/refs/chebfun1d_extras_refs.m
(-> tests/references/chebfun1d_extras.mat).
"""

from pathlib import Path

import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest

import chebfunjax as cj
from chebfunjax.chebfun1d.chebfun import Chebfun, ode45, ode113
from chebfunjax.chebfun1d.linalg import chebfun_qr, chebfun_svd

_REF_PATH = Path(__file__).resolve().parents[1] / "references" / "chebfun1d_extras.mat"
if not _REF_PATH.exists():
    pytest.skip(
        "chebfun1d_extras.mat golden ref not generated "
        "(run matlab_harness/refs/chebfun1d_extras_refs.m)",
        allow_module_level=True,
    )

import scipy.io  # noqa: E402  (only needed once the ref exists)

_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_PTS = jnp.asarray(_REF["pts"], dtype=jnp.float64)

RTOL = 1e-12


def _evec(f) -> np.ndarray:
    """Evaluate a Chebfun at the shared points as a numpy array."""
    return np.asarray(f(_PTS))


# ---------------------------------------------------------------------------
# Special functions: composition then evaluation
# ---------------------------------------------------------------------------


@pytest.mark.matlab
class TestSpecialFunctions:
    def test_besselj0(self):
        f = cj.chebfun(lambda t: 0.5 * t + 0.3).besselj(0)
        npt.assert_allclose(_evec(f), _REF["besselj0"], rtol=RTOL, atol=1e-13)

    def test_besselj1(self):
        f = cj.chebfun(lambda t: 0.5 * t + 0.3).besselj(1)
        npt.assert_allclose(_evec(f), _REF["besselj1"], rtol=RTOL, atol=1e-13)

    def test_bessely1(self):
        f = cj.chebfun(lambda t: 0.5 * t + 1.0).bessely(1)
        npt.assert_allclose(_evec(f), _REF["bessely1"], rtol=RTOL, atol=1e-13)

    def test_airy_ai(self):
        f = cj.chebfun(lambda t: t).airy(0)
        npt.assert_allclose(_evec(f), _REF["airy_Ai"], rtol=RTOL, atol=1e-13)

    def test_airy_bi(self):
        f = cj.chebfun(lambda t: t).airy(2)
        npt.assert_allclose(_evec(f), _REF["airy_Bi"], rtol=RTOL, atol=1e-13)

    def test_erf(self):
        f = cj.chebfun(lambda t: 2.0 * t).erf()
        npt.assert_allclose(_evec(f), _REF["erf"], rtol=RTOL, atol=1e-13)

    def test_erfc(self):
        f = cj.chebfun(lambda t: 2.0 * t).erfc()
        npt.assert_allclose(_evec(f), _REF["erfc"], rtol=RTOL, atol=1e-13)


# ---------------------------------------------------------------------------
# polyfit — STRICT XFAIL (Chebyshev-vs-Legendre truncation bug)
# ---------------------------------------------------------------------------


@pytest.mark.matlab
# polyfit now truncates the LEGENDRE series like MATLAB (bug fixed).
def test_polyfit_exp5():
    p = cj.chebfun(lambda t: jnp.exp(t)).polyfit(5)
    npt.assert_allclose(_evec(p), _REF["polyfit_exp5"], rtol=RTOL, atol=1e-13)


# ---------------------------------------------------------------------------
# interp1 / spline / pchip — data interpolants
# ---------------------------------------------------------------------------


@pytest.mark.matlab
class TestInterpolants:
    def test_interp1(self):
        xi = jnp.asarray(_REF["interp1_xi"], dtype=jnp.float64)
        yi = jnp.asarray(_REF["interp1_yi"], dtype=jnp.float64)
        p = Chebfun.interp1(xi, yi)
        npt.assert_allclose(_evec(p), _REF["interp1"], rtol=RTOL, atol=1e-13)

    def test_spline(self):
        xs = jnp.asarray(_REF["spline_xs"], dtype=jnp.float64)
        ys = jnp.asarray(_REF["spline_ys"], dtype=jnp.float64)
        f = Chebfun.spline(xs, ys)
        npt.assert_allclose(_evec(f), _REF["spline"], rtol=RTOL, atol=1e-13)

    def test_pchip(self):
        xs = jnp.asarray(_REF["spline_xs"], dtype=jnp.float64)
        ys = jnp.asarray(_REF["spline_ys"], dtype=jnp.float64)
        f = Chebfun.pchip(xs, ys)
        npt.assert_allclose(_evec(f), _REF["pchip"], rtol=RTOL, atol=1e-13)


# ---------------------------------------------------------------------------
# conv — convolution of two chebfuns
# ---------------------------------------------------------------------------


@pytest.mark.matlab
class TestConv:
    def _h(self):
        f = cj.chebfun(lambda t: jnp.sin(t))
        g = cj.chebfun(lambda t: jnp.exp(t))
        return f.conv(g)

    def test_domain(self):
        h = self._h()
        got = np.array([float(h.domain.a), float(h.domain.b)])
        npt.assert_allclose(got, np.asarray(_REF["conv_dom"], dtype=float),
                            rtol=RTOL, atol=1e-13)

    def test_eval(self):
        h = self._h()
        cpts = jnp.asarray(_REF["conv_pts"], dtype=jnp.float64)
        npt.assert_allclose(np.asarray(h(cpts)), _REF["conv_eval"],
                            rtol=RTOL, atol=1e-11)


# ---------------------------------------------------------------------------
# cumsum / diff chains, sum, norm
# ---------------------------------------------------------------------------


@pytest.mark.matlab
class TestCalculusChains:
    def _fc(self):
        return cj.chebfun(lambda t: jnp.cos(3.0 * t))

    def test_cumsum(self):
        npt.assert_allclose(_evec(self._fc().cumsum()), _REF["cumsum"],
                            rtol=RTOL, atol=1e-13)

    def test_diff1(self):
        npt.assert_allclose(_evec(self._fc().diff()), _REF["diff1"],
                            rtol=RTOL, atol=1e-13)

    def test_diff2(self):
        npt.assert_allclose(_evec(self._fc().diff(2)), _REF["diff2"],
                            rtol=RTOL, atol=1e-13)

    def test_sum(self):
        npt.assert_allclose(float(self._fc().sum()), float(_REF["sum"]),
                            rtol=RTOL, atol=1e-13)

    def test_norm(self):
        npt.assert_allclose(float(self._fc().norm()), float(_REF["norm2"]),
                            rtol=RTOL, atol=1e-13)


# ---------------------------------------------------------------------------
# Quasimatrix qr / svd of A = [1, x, x^2, x^3] on [-1, 1]
# ---------------------------------------------------------------------------


def _quasimatrix_cols():
    return [cj.chebfun(lambda t, k=k: t**k) for k in range(4)]


@pytest.mark.matlab
class TestQuasimatrixLinalg:
    def test_svd_singular_values(self):
        _, S, _ = chebfun_svd(_quasimatrix_cols())
        npt.assert_allclose(np.asarray(S), _REF["svd_S"], rtol=RTOL, atol=1e-13)

    def test_qr_rdiag(self):
        _, R = chebfun_qr(_quasimatrix_cols())
        npt.assert_allclose(np.diag(np.asarray(R)), _REF["qr_Rdiag"],
                            rtol=RTOL, atol=1e-13)

    def test_qr_r_full(self):
        _, R = chebfun_qr(_quasimatrix_cols())
        npt.assert_allclose(np.asarray(R), _REF["qr_R"], rtol=RTOL, atol=1e-12)


# ---------------------------------------------------------------------------
# ode45 / ode113 — accuracy of an IVP solve (documented Gate-3 metric)
# ---------------------------------------------------------------------------

# scipy solve_ivp adaptive step control (rtol 1e-6) => NOT a 1e-12 pin; the
# reference is the analytic solution and we check solver accuracy only.
_ODE_RTOL = 1e-5
_ODE_ATOL = 1e-6


@pytest.mark.matlab
class TestODEAccuracy:
    def _eval(self, sol):
        tt = np.asarray(_REF["ode_t"], dtype=float)
        return np.array([float(sol(jnp.float64(t))) for t in tt])

    def test_ode45_decay(self):
        sol = ode45(lambda t, y: -y, (0.0, 2.0), jnp.array([1.0]))
        npt.assert_allclose(self._eval(sol), _REF["ode_exact"],
                            rtol=_ODE_RTOL, atol=_ODE_ATOL)

    def test_ode113_decay(self):
        sol = ode113(lambda t, y: -y, (0.0, 2.0), jnp.array([1.0]))
        npt.assert_allclose(self._eval(sol), _REF["ode_exact"],
                            rtol=_ODE_RTOL, atol=_ODE_ATOL)
