"""Every expinteg time-stepping scheme against MATLAB (Fable 5).

Golden ref generated by ``matlab_harness/refs/spin_schemes_refs.m``
(-> spin_schemes.mat): KdV with all 31 schemes of @expinteg/expinteg.m
and Gray-Scott with eight of them, MATLAB's default ``dealias = 'off'``.

Provenance
----------
MATLAB source : @expinteg/{computeCoeffs,oneStep,startMultistep}.m,
    @spinoperator/solvepde.m
Chebfun commit: 7574c77
"""

from __future__ import annotations

from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import pytest
import scipy.io

from chebfunjax.operators.spinop import Spinop, spin
from chebfunjax.operators.spinop2 import Spinop2, spin2

jax.config.update("jax_enable_x64", True)

_REF_PATH = Path(__file__).resolve().parents[1] / "references" / "spin_schemes.mat"
if not _REF_PATH.exists():
    pytest.skip("spin_schemes.mat golden ref not generated "
                "(run matlab_harness/refs/spin_schemes_refs.m)",
                allow_module_level=True)
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)

_KDV_SCHEMES = [str(s).strip() for s in _REF["kdv_schemes"]]
_GS_SCHEMES = [str(s).strip() for s in _REF["gs_schemes"]]


@pytest.mark.parametrize("k", range(len(_KDV_SCHEMES)), ids=_KDV_SCHEMES)
def test_kdv_scheme_matches_matlab(k):
    N = int(_REF["kdv_N"])
    dt = float(_REF["kdv_dt"])
    nsteps = int(_REF["kdv_nsteps"])
    S = Spinop("KDV")
    S.tspan = (0.0, nsteps * dt)
    x = jnp.asarray(-np.pi + 2 * np.pi * np.arange(N) / N)
    u = np.asarray(spin(S, N, dt, "plot", "off", "dealias", "off",
                        scheme=_KDV_SCHEMES[k])(x))
    ref = np.asarray(_REF["kdv_u"])[:, k]
    assert np.max(np.abs(u - ref)) / np.max(np.abs(ref)) < 1e-12


@pytest.mark.parametrize("k", range(len(_GS_SCHEMES)), ids=_GS_SCHEMES)
def test_gray_scott_scheme_matches_matlab(k):
    N = int(_REF["gs_N"])
    dt = float(_REF["gs_dt"])
    nsteps = int(_REF["gs_nsteps"])
    S = Spinop2("GS")
    S.tspan = (0.0, nsteps * dt)
    u = spin2(S, N, dt, "plot", "off", "dealias", "off", scheme=_GS_SCHEMES[k])
    g = jnp.asarray(np.arange(0, N, 4) / N)
    XX, YY = jnp.meshgrid(g, g)                      # MATLAB meshgrid (xy)
    ref = np.asarray(_REF["gs_uv_sub4"])
    n_sub = ref.shape[0]
    m = int(round(np.sqrt(n_sub)))
    for c in range(2):
        r = ref[:, 2 * k + c].reshape(m, m, order="F")
        v = np.asarray(u.components[c](XX, YY))
        assert np.max(np.abs(v - r)) / np.max(np.abs(r)) < 1e-10
