"""MATLAB golden-reference parity tests for the spin package (1D ETDRK4).

Pins ``chebfunjax.spin.spin`` (ETDRK4 exponential time-stepping, Fourier
spectral discretization) against MATLAB Chebfun ``spin`` at rtol 1e-12.
Golden ref generated by ``matlab_harness/refs/spin_refs.m`` (-> spin.mat).

Convention matching (verified against the Chebfun @spinop/@expinteg source):
  * grid           trigpts(N, dom) == np.linspace(a, b, N, endpoint=False)
  * vals<->coeffs   fft / ifft (Chebfun getVals2/Coeffs2Transform)
  * dealiasing      OFF   (Chebfun spinpref default -> chebfunjax dealias=False)
  * contour pts M   64    (Chebfun spinpref default -> chebfunjax M=64)
  * scheme          etdrk4 (Chebfun spinpref default)
  * step count      tf = nsteps*dt exactly (both do round(tf/dt) steps)

Result summary (see the module for the two strict-pass and two xfail cases):
  * LINEAR cases (N(u) = 0) match at 1e-12 -- for a linear operator ETDRK4
    reduces to u_hat <- exp(dt*L) u_hat, independent of the phi-function
    machinery, so the two implementations are algebraically identical.
  * NONLINEAR cases DIVERGE at the O(1e-1) level.  This is NOT chaotic
    sensitivity (the runs are short and well-posed): it is a genuine bug in
    chebfunjax's ETDRK4 stage structure -- see BUG note below.  Those cases
    are strict-xfail so the suite stays green while the bug is tracked; when
    the library is fixed the xfail flips to a failure and must be removed.

BUG (reported to team lead) -- chebfunjax.spin.solver._etdrk4_step:
  MATLAB Chebfun's etdrk4 calls computeMissingCoeffs (@expinteg/computeCoeffs.m
  lines 1367-1372), which fills in the stage-1 nonlinear coefficients via the
  row-summation property:
      A{2,1} = psi_{1,1/2}
      A{4,1} = psi_{1,1} - 2*psi_{1,1/2}
      B{1}   = phi_1 - 3*phi_2 + 4*phi_3
  chebfunjax's _etdrk4_step OMITS all three N(u_n) contributions (its docstring
  incorrectly asserts Chebfun's etdrk4 has "no nonlinear forcing from u_n").
  Consequently every nonlinear PDE integrates with a different (and non-4th-order)
  scheme.  Measured on the Allen-Cahn case below (N=64, dt=0.05, 20 steps):
      max|chebfunjax - MATLAB| = 6.4e-2   (7.6% relative)
  Fix: add A{2,1}, A{4,1}, B{1} to the stage/update formulas in _etdrk4_step
  (and _compute_etdrk4_coeffs), mirroring computeMissingCoeffs.
"""

from pathlib import Path

import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

from chebfunjax.spin import SpinOp, spin

_REF_PATH = Path(__file__).resolve().parents[1] / "references" / "spin.mat"
if not _REF_PATH.exists():
    pytest.skip(
        "spin.mat golden ref not generated (run matlab_harness/refs/spin_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)

RTOL = 1e-12
ATOL = 1e-12

# ---------------------------------------------------------------------------
# Case definitions -- these mirror matlab_harness/refs/spin_refs.m EXACTLY.
# lin_coeff takes xi = (2*pi/L)*k (Chebfun trigspec convention), so
# `c*diff(u,m)` maps to `lambda xi: c*(1j*xi)**m`.
# ---------------------------------------------------------------------------
_CASES = {
    # --- LINEAR (N(u) = 0): ETDRK4 exact up to exp(dt*L) -> strict 1e-12 ---
    "lin_diff": dict(
        lin_coeff=lambda xi: 0.05 * (1j * xi) ** 2,
        nonlin_vals=lambda u: 0.0 * u,
        nonlin_diff_order=0,
        u0=lambda x: jnp.sin(x) + 0.5 * jnp.cos(2.0 * x),
        is_real=True,
    ),
    "lin_schrod": dict(
        lin_coeff=lambda xi: 1j * (1j * xi) ** 2,
        nonlin_vals=lambda u: 0.0 * u,
        nonlin_diff_order=0,
        u0=lambda x: 1.0 + 0.6 * jnp.cos(x) + 0.3 * jnp.sin(2.0 * x),
        is_real=False,
    ),
    # --- NONLINEAR short, well-posed (NOT chaotic) -> BUG, strict xfail ---
    "allen_cahn": dict(
        lin_coeff=lambda xi: 5e-3 * (1j * xi) ** 2,
        nonlin_vals=lambda u: u - u**3,
        nonlin_diff_order=0,
        u0=lambda x: 0.5 * jnp.sin(x),
        is_real=True,
    ),
    "nls": dict(
        lin_coeff=lambda xi: 1j * (1j * xi) ** 2,
        nonlin_vals=lambda u: 1j * jnp.abs(u) ** 2 * u,
        nonlin_diff_order=0,
        u0=lambda x: 1.0 + 0.5 * jnp.cos(x),
        is_real=False,
    ),
}

_BUG_REASON = (
    "chebfunjax.spin.solver._etdrk4_step omits the stage-1 nonlinear terms "
    "A{2,1}, A{4,1}, B{1} that Chebfun's computeMissingCoeffs fills in; "
    "nonlinear spin runs use a different scheme (~8% off MATLAB). Reported."
)


def _run(case: str):
    """Build the SpinOp for *case* from the ref's exact N/dt/dom/tf and run spin.

    Returns (x, u_final) with dealias off and M=64 to match Chebfun's spinpref
    defaults.  Also asserts the chebfunjax grid equals the MATLAB trigpts grid.
    """
    c = _CASES[case]
    dom = tuple(float(v) for v in np.atleast_1d(_REF[f"{case}_dom"]))
    N = int(_REF[f"{case}_N"])
    dt = float(_REF[f"{case}_dt"])
    tf = float(_REF[f"{case}_tf"])
    op = SpinOp(
        lin_coeff=c["lin_coeff"],
        nonlin_vals=c["nonlin_vals"],
        nonlin_diff_order=c["nonlin_diff_order"],
        domain=dom,
        tspan=(0.0, tf),
        u0=c["u0"],
        is_real=c["is_real"],
    )
    x, _t, u = spin(op, N, dt, dealias=False, M=64)
    # Grid must coincide with MATLAB trigpts(N, dom) or the comparison is void.
    npt.assert_allclose(np.asarray(x), np.asarray(_REF[f"{case}_x"]),
                        rtol=0, atol=1e-14)
    return np.asarray(x), np.asarray(u)


@pytest.mark.matlab
class TestSpin1DVsMatlab:
    """Golden-ref parity for chebfunjax.spin.spin vs MATLAB Chebfun spin."""

    @pytest.mark.parametrize("case", ["lin_diff", "lin_schrod"])
    def test_linear_exact(self, case):
        # Linear (N(u)=0): ETDRK4 collapses to exp(dt*L) -> exact 1e-12 parity.
        _x, u = _run(case)
        npt.assert_allclose(u, _REF[f"{case}_u"], rtol=RTOL, atol=ATOL)

    @pytest.mark.parametrize(
        "case",
        [
            # Previously strict-xfail: the ETDRK4 stage-1 nonlinear terms
            # (A{2,1}, A{4,1}, B{1}) were missing; restored to the MATLAB
            # computeMissingCoeffs scheme, these now hit 1e-12 parity.
            "allen_cahn",
            "nls",
        ],
    )
    def test_nonlinear_parity(self, case):
        # Short, well-posed, non-chaotic nonlinear runs.  Parity target is
        # 1e-12; they currently FAIL by ~1e-1 due to the _etdrk4_step bug
        # documented at the top of this file (NOT chaotic sensitivity).
        _x, u = _run(case)
        npt.assert_allclose(u, _REF[f"{case}_u"], rtol=RTOL, atol=ATOL)
