"""MATLAB golden-reference parity tests for the ballfun vector module (Ballfunv).

Pins the 3D vector operations on the unit ball against MATLAB Ballfunv at
rtol 1e-12: component evaluation, dot, cross, and the (scalar) L2/Frobenius
norm.  Golden ref generated by matlab_harness/refs/ballfunv_refs.m
(-> tests/references/ballfunv.mat).

Convention: components built Cartesian (op(x,y,z)), evaluated in spherical
coords f(r, lam, th) with x=r sin(th)cos(lam), y=r sin(th)sin(lam), z=r cos(th).
Ballfun/Ballfunv __call__ does a meshgrid eval, so a single matched point is
read as [0, 0, 0].  Ballfunv.norm() is a scalar, matching MATLAB norm(F).
"""

from pathlib import Path

import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

from chebfunjax.ballfun.ballfunv import Ballfunv

_REF_PATH = Path(__file__).resolve().parents[1] / "references" / "ballfunv.mat"
if not _REF_PATH.exists():
    pytest.skip(
        "ballfunv.mat golden ref not generated "
        "(run matlab_harness/refs/ballfunv_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_RP = np.atleast_1d(_REF["rp"]).astype(float)
_LAMP = np.atleast_1d(_REF["lamp"]).astype(float)
_THP = np.atleast_1d(_REF["thp"]).astype(float)

RTOL = 1e-12


def _F():
    return Ballfunv.from_functions(
        lambda x, y, z: z,
        lambda x, y, z: x,
        lambda x, y, z: 1 + x * z,
    )


def _G():
    return Ballfunv.from_functions(
        lambda x, y, z: x,
        lambda x, y, z: z,
        lambda x, y, z: 1.0 + 0 * x,
    )


def _eval_scalar(f):
    """Evaluate a scalar Ballfun at the matched (r, lam, th) points (grid -> [0,0,0])."""
    out = np.empty(_RP.shape[0], dtype=float)
    for k in range(_RP.shape[0]):
        val = f(jnp.array([_RP[k]]), jnp.array([_LAMP[k]]), jnp.array([_THP[k]]))
        out[k] = float(np.real(np.asarray(val)[0, 0, 0]))
    return out


def _eval_vector(F):
    """Evaluate a Ballfunv at the matched points, returning (m,3) real values."""
    out = np.empty((_RP.shape[0], 3), dtype=float)
    for k in range(_RP.shape[0]):
        vals = F(jnp.array([_RP[k]]), jnp.array([_LAMP[k]]), jnp.array([_THP[k]]))
        for j in range(3):
            out[k, j] = float(np.real(np.asarray(vals[j])[0, 0, 0]))
    return out


@pytest.mark.matlab
class TestBallfunvVsMatlab:
    def test_component_eval(self):
        vals = _eval_vector(_F())
        npt.assert_allclose(vals[:, 0], _REF["F1_eval"], rtol=RTOL, atol=1e-12)
        npt.assert_allclose(vals[:, 1], _REF["F2_eval"], rtol=RTOL, atol=1e-12)
        npt.assert_allclose(vals[:, 2], _REF["F3_eval"], rtol=RTOL, atol=1e-12)

    def test_dot(self):
        d = _F().dot(_G())
        npt.assert_allclose(_eval_scalar(d), _REF["dot_eval"], rtol=RTOL, atol=1e-12)

    def test_cross(self):
        vals = _eval_vector(_F().cross(_G()))
        npt.assert_allclose(vals[:, 0], _REF["crossx_eval"], rtol=RTOL, atol=1e-12)
        npt.assert_allclose(vals[:, 1], _REF["crossy_eval"], rtol=RTOL, atol=1e-12)
        npt.assert_allclose(vals[:, 2], _REF["crossz_eval"], rtol=RTOL, atol=1e-12)

    def test_norm_frobenius(self):
        npt.assert_allclose(float(_F().norm()), float(_REF["normF"]), rtol=RTOL)
