"""MATLAB golden-reference parity tests for the ballfun vector module (Ballfunv).

Pins the 3D vector operations on the unit ball against MATLAB Ballfunv at
rtol 1e-12: component evaluation, dot, cross, and the (scalar) L2/Frobenius
norm.  Golden ref generated by matlab_harness/refs/ballfunv_refs.m
(-> tests/references/ballfunv.mat).

Convention: components built Cartesian (op(x,y,z)), evaluated in spherical
coords f(r, lam, th) with x=r sin(th)cos(lam), y=r sin(th)sin(lam), z=r cos(th).
Ballfun/Ballfunv __call__ does a meshgrid eval, so a single matched point is
read as [0, 0, 0].  Ballfunv.norm() is a scalar, matching MATLAB norm(F).
"""

from pathlib import Path

import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

from chebfunjax.ballfun.ballfunv import Ballfunv

_REF_PATH = Path(__file__).resolve().parents[1] / "references" / "ballfunv.mat"
if not _REF_PATH.exists():
    pytest.skip(
        "ballfunv.mat golden ref not generated "
        "(run matlab_harness/refs/ballfunv_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_RP = np.atleast_1d(_REF["rp"]).astype(float)
_LAMP = np.atleast_1d(_REF["lamp"]).astype(float)
_THP = np.atleast_1d(_REF["thp"]).astype(float)

RTOL = 1e-12


def _F():
    return Ballfunv.from_functions(
        lambda x, y, z: z,
        lambda x, y, z: x,
        lambda x, y, z: 1 + x * z,
    )


def _G():
    return Ballfunv.from_functions(
        lambda x, y, z: x,
        lambda x, y, z: z,
        lambda x, y, z: 1.0 + 0 * x,
    )


def _eval_scalar(f):
    """Evaluate a scalar Ballfun at the matched (r, lam, th) points (grid -> [0,0,0])."""
    out = np.empty(_RP.shape[0], dtype=float)
    for k in range(_RP.shape[0]):
        val = f(jnp.array([_RP[k]]), jnp.array([_LAMP[k]]), jnp.array([_THP[k]]))
        out[k] = float(np.real(np.asarray(val)[0, 0, 0]))
    return out


def _eval_vector(F):
    """Evaluate a Ballfunv at the matched points, returning (m,3) real values."""
    out = np.empty((_RP.shape[0], 3), dtype=float)
    for k in range(_RP.shape[0]):
        vals = F(jnp.array([_RP[k]]), jnp.array([_LAMP[k]]), jnp.array([_THP[k]]))
        for j in range(3):
            out[k, j] = float(np.real(np.asarray(vals[j])[0, 0, 0]))
    return out


@pytest.mark.matlab
class TestBallfunvVsMatlab:
    def test_component_eval(self):
        vals = _eval_vector(_F())
        npt.assert_allclose(vals[:, 0], _REF["F1_eval"], rtol=RTOL, atol=1e-12)
        npt.assert_allclose(vals[:, 1], _REF["F2_eval"], rtol=RTOL, atol=1e-12)
        npt.assert_allclose(vals[:, 2], _REF["F3_eval"], rtol=RTOL, atol=1e-12)

    def test_dot(self):
        d = _F().dot(_G())
        npt.assert_allclose(_eval_scalar(d), _REF["dot_eval"], rtol=RTOL, atol=1e-12)

    def test_cross(self):
        vals = _eval_vector(_F().cross(_G()))
        npt.assert_allclose(vals[:, 0], _REF["crossx_eval"], rtol=RTOL, atol=1e-12)
        npt.assert_allclose(vals[:, 1], _REF["crossy_eval"], rtol=RTOL, atol=1e-12)
        npt.assert_allclose(vals[:, 2], _REF["crossz_eval"], rtol=RTOL, atol=1e-12)

    def test_norm_frobenius(self):
        npt.assert_allclose(float(_F().norm()), float(_REF["normF"]), rtol=RTOL)


class TestBallfunvDivCurl:
    """Ballfunv divergence/curl via Ballfun Cartesian diff (Opus 4.8, #17)."""

    _pts = [(0.3, 0.4, 0.5), (0.6, 1.0, 2.0), (0.8, -1.5, 1.2)]

    def _ev(self, bf):
        import jax.numpy as jnp
        import numpy as np
        return np.array([float(bf(jnp.array(r), jnp.array(lam), jnp.array(t)))
                         for r, lam, t in self._pts])

    def test_div_curl_identities(self):
        import numpy as np

        from chebfunjax.ballfun.ballfunv import Ballfunv
        # F = (x, y, z): div = 3, curl = 0
        V = Ballfunv.from_functions(lambda x, y, z: x, lambda x, y, z: y,
                                    lambda x, y, z: z)
        np.testing.assert_allclose(self._ev(V.div()), 3.0, atol=1e-9)
        for cc in V.curl().components:
            np.testing.assert_allclose(self._ev(cc), 0.0, atol=1e-8)
        # F = (-y, x, 0): div = 0, curl = (0, 0, 2)
        W = Ballfunv.from_functions(lambda x, y, z: -y, lambda x, y, z: x,
                                    lambda x, y, z: 0 * x)
        np.testing.assert_allclose(self._ev(W.div()), 0.0, atol=1e-8)
        cw = W.curl().components
        np.testing.assert_allclose(self._ev(cw[0]), 0.0, atol=1e-8)
        np.testing.assert_allclose(self._ev(cw[1]), 0.0, atol=1e-8)
        np.testing.assert_allclose(self._ev(cw[2]), 2.0, atol=1e-8)

    def test_div_of_curl_is_zero(self):
        import numpy as np

        from chebfunjax.ballfun.ballfunv import Ballfunv
        G = Ballfunv.from_functions(lambda x, y, z: x * y,
                                    lambda x, y, z: y * z,
                                    lambda x, y, z: x * z)
        np.testing.assert_allclose(self._ev(G.curl().div()), 0.0, atol=1e-7)


class TestBallfunvHelmholtz:
    """Helmholtz (Hodge) decomposition on the ball (Opus 4.8, task #17)."""

    _pts = [(0.3, 0.4, 0.5), (0.6, 1.0, 2.0), (0.7, -1.5, 1.2)]

    def _ev(self, bf):
        import jax.numpy as jnp
        import numpy as np
        return np.array([float(bf(jnp.array(r), jnp.array(lam), jnp.array(t)))
                         for r, lam, t in self._pts])

    def test_decomposition(self):
        import numpy as np

        from chebfunjax.ballfun.ballfunv import Ballfunv
        F = Ballfunv.from_functions(lambda x, y, z: x ** 2,
                                    lambda x, y, z: y * z,
                                    lambda x, y, z: x)
        phi, curl_free, div_free = F.helmholtz_decomposition(lmax=8, nr=28)
        # div-free part has zero divergence
        np.testing.assert_allclose(self._ev(div_free.div()), 0.0, atol=1e-7)
        # exact reconstruction F = grad(phi) + div_free
        for i in range(3):
            rec = self._ev(curl_free.components[i]) \
                + self._ev(div_free.components[i])
            np.testing.assert_allclose(rec, self._ev(F.components[i]),
                                       atol=1e-9)
