"""MATLAB golden-reference parity tests for the diskfun vector module (Diskfunv).

Pins the vector operations on the unit disk against MATLAB Diskfunv at rtol
1e-12: component evaluation, dot, and the pointwise Euclidean magnitude.
Golden ref generated by matlab_harness/refs/diskfunv_refs.m
(-> tests/references/diskfunv.mat).

Convention: polar-native components f(theta, r), theta in [-pi,pi], r in [0,1];
MATLAB refs built with 'polar' and feval(f,theta,r,'polar').  Both chebfunjax
and MATLAB diskfunv are 2-component and dot = F1*G1 + F2*G2.

NOTE: chebfunjax Diskfunv.norm() returns the POINTWISE magnitude sqrt(f^2+g^2)
as a Diskfun, whereas MATLAB @diskfunv/norm returns the Frobenius SCALAR.  We
pin the pointwise field (using a field bounded away from 0 so it resolves); the
MATLAB Frobenius scalar is stored as norm_frob for documentation only.
"""

from pathlib import Path

import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

from chebfunjax.diskfun.diskfunv import Diskfunv

_REF_PATH = Path(__file__).resolve().parents[1] / "references" / "diskfunv.mat"
if not _REF_PATH.exists():
    pytest.skip(
        "diskfunv.mat golden ref not generated "
        "(run matlab_harness/refs/diskfunv_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_T = jnp.asarray(_REF["tpts"], dtype=jnp.float64)
_R = jnp.asarray(_REF["rpts"], dtype=jnp.float64)

RTOL = 1e-12


def _F():
    return Diskfunv.from_functions(
        lambda t, r: r * jnp.cos(t),
        lambda t, r: r * jnp.sin(t),
    )


def _G():
    return Diskfunv.from_functions(
        lambda t, r: r**2,
        lambda t, r: r * jnp.cos(t),
    )


def _N():
    # Field bounded away from 0: [2+x, y] — smooth magnitude, resolvable.
    return Diskfunv.from_functions(
        lambda t, r: 2.0 + r * jnp.cos(t),
        lambda t, r: r * jnp.sin(t),
    )


@pytest.mark.matlab
class TestDiskfunvVsMatlab:
    def test_component_eval(self):
        f_val, g_val = _F()(_T, _R)
        npt.assert_allclose(np.asarray(f_val), _REF["F1_eval"], rtol=RTOL, atol=1e-12)
        npt.assert_allclose(np.asarray(g_val), _REF["F2_eval"], rtol=RTOL, atol=1e-12)

    def test_dot(self):
        d = _F().dot(_G())
        npt.assert_allclose(np.asarray(d(_T, _R)), _REF["dot_eval"],
                            rtol=RTOL, atol=1e-12)

    def test_norm_pointwise(self):
        # Diskfunv.norm() returns the pointwise magnitude field sqrt(f^2+g^2).
        n = _N().norm()
        npt.assert_allclose(np.asarray(n(_T, _R)), _REF["norm_eval"],
                            rtol=RTOL, atol=1e-12)


class TestDiskfunvDivCurl:
    """Diskfunv divergence/curl via Diskfun Cartesian calculus (Opus 4.8).

    Verified against exact identities: div(x,y)=2, curl(x,y)=0,
    div(-y,x)=0, curl(-y,x)=2.
    """

    def _pts(self):
        import jax.numpy as jnp
        tt = jnp.linspace(-3.0, 3.0, 7)
        rr = jnp.linspace(0.15, 0.9, 7)
        T, R = jnp.meshgrid(tt, rr)
        return T.ravel(), R.ravel()

    def test_div_curl_identities(self):
        import warnings

        import jax.numpy as jnp
        import numpy as np

        from chebfunjax.diskfun.diskfunv import Diskfunv
        T, R = self._pts()
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            # F = (x, y): div = 2, curl = 0
            V = Diskfunv.from_functions(lambda t, r: r * jnp.cos(t),
                                        lambda t, r: r * jnp.sin(t))
            np.testing.assert_allclose(np.asarray(V.div()(T, R)),
                                       2.0 * np.ones(T.shape), atol=1e-9)
            np.testing.assert_allclose(np.asarray(V.curl()(T, R)),
                                       np.zeros(T.shape), atol=1e-9)
            # F = (-y, x): div = 0, curl = 2
            W = Diskfunv.from_functions(lambda t, r: -r * jnp.sin(t),
                                        lambda t, r: r * jnp.cos(t))
            np.testing.assert_allclose(np.asarray(W.div()(T, R)),
                                       np.zeros(T.shape), atol=1e-9)
            np.testing.assert_allclose(np.asarray(W.curl()(T, R)),
                                       2.0 * np.ones(T.shape), atol=1e-9)
