"""MATLAB golden-reference parity tests for the spectral discretization
operators that were UNCOVERED by ``test_chebcolloc.py`` (which already pins
chebcolloc1/chebcolloc2).

Pins the raw dense operator matrices ENTRYWISE at rtol 1e-12 against MATLAB
Chebfun (commit 7574c77):

* ``@ultraS`` : ``diffmat`` (Cheb-T -> C^{(m)}), ``convertmat`` (C^{(k1)} ->
  C^{(k2+1)}), ``multmat`` (multiplication in the C^{(lambda)} basis).
* ``@trigcolloc`` : ``diffmat`` (Fourier pseudospectral, both parities and the
  FFT branch), equispaced ``trigpts`` and trapezoidal ``quadwts``.

Golden ref generated by ``matlab_harness/refs/discretization_refs.m``
(-> ``tests/references/discretization.mat``).

Tolerance convention
--------------------
Every operator is compared with ``rtol = 1e-12`` and an absolute floor
``atol = 1e-12 * max(1, ||ref||_max)`` — i.e. 1e-12 *relative to the operator's
own scale*.  This is the standard, defensible way to compare two independent
floating-point matrix computations: it is tight enough to catch any real bug
(the confirmed ``multmat`` bug below misses by ~1e-1, a transpose/permutation
would miss by O(1)), yet it absorbs the ~1e-16-relative FFT-implementation
roundoff that MATLAB's FFTW and JAX's FFT accumulate in the ``trig_diffmat``
m>=5 branch (abs diff ~1e-10 on entries of magnitude ~1e6).  It is NOT a
tolerance widening: the analytic branches all agree to ~1e-16 relative.

Findings (see the module-level agent report for full repros):

* ``ultraS.multmat`` for ``lambda >= 2`` is a CONFIRMED BUG in chebfunjax
  (``src/chebfunjax/discretization/ultras.py``).  Two independent off-by-one
  errors in the ``lambda >= 2`` three-term-recurrence branch:
    1. the recurrence loop is 0-indexed but the Gegenbauer factors
       ``2*(nn+lam)/(nn+1)`` and ``(nn+2*lam-1)/(nn+1)`` need MATLAB's
       1-indexed ``nn``;
    2. the multiplication-by-x matrix ``Mx`` superdiagonal uses ``d1[:m-1]``
       whereas MATLAB ``spdiags(B,[-1 0 1])`` positive-offset alignment
       requires ``d1[1:m]``.
  Fixing BOTH reproduces MATLAB to 1.1e-16.  ``lambda = 0`` and ``lambda = 1``
  are correct.  The failing cases are marked ``xfail(strict=True)`` so the
  suite stays green while the bug is tracked; remove the marks when the library
  fix lands.
"""

from pathlib import Path

import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

from chebfunjax.discretization import trigcolloc, ultras
from chebfunjax.discretization.trigcolloc import TrigColloc
from chebfunjax.domain import Domain

_REF_PATH = Path(__file__).resolve().parents[1] / "references" / "discretization.mat"
if not _REF_PATH.exists():
    pytest.skip(
        "discretization.mat golden ref not generated "
        "(run matlab_harness/refs/discretization_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)

RTOL = 1e-12


def _assert_close(got, key):
    """Entrywise parity at rtol 1e-12, scale-aware absolute floor."""
    ref = np.asarray(_REF[key], dtype=np.float64)
    got = np.asarray(got, dtype=np.float64)
    assert got.shape == ref.shape, f"{key}: shape {got.shape} vs ref {ref.shape}"
    atol = 1e-12 * max(1.0, float(np.max(np.abs(ref))))
    npt.assert_allclose(got, ref, rtol=RTOL, atol=atol, err_msg=key)


# ---------------------------------------------------------------------------
# ultraS: differentiation matrices  (Chebyshev T coeffs -> C^{(m)} coeffs)
# ---------------------------------------------------------------------------
@pytest.mark.matlab
@pytest.mark.parametrize("n", [8, 12])
@pytest.mark.parametrize("m", [1, 2, 3])
def test_ultras_diffmat(n, m):
    _assert_close(ultras.diffmat(n, m), f"us_diff_n{n}_m{m}")


# ---------------------------------------------------------------------------
# ultraS: conversion matrices  C^{(k1)} -> C^{(k2+1)}
# ---------------------------------------------------------------------------
@pytest.mark.matlab
@pytest.mark.parametrize("n", [8, 12])
@pytest.mark.parametrize("k1,k2", [(0, 0), (0, 1), (1, 1), (0, 2), (1, 2), (2, 2)])
def test_ultras_convertmat(n, k1, k2):
    _assert_close(ultras.convertmat(n, k1, k2), f"us_conv_n{n}_{k1}_{k2}")


# ---------------------------------------------------------------------------
# ultraS: multiplication matrices in the C^{(lambda)} basis
#   lambda = 0, 1 are correct; lambda >= 2 is a confirmed off-by-one bug.
# ---------------------------------------------------------------------------
_MULT_COEFFS = jnp.asarray(_REF["us_mult_coeffs"], dtype=jnp.float64)
# multmat lambda>=2 off-by-one bugs fixed (recurrence index + spdiags
# superdiagonal + nnz early-stop); all lambdas now match MATLAB to 1e-16.
_XFAIL_MULT = []


@pytest.mark.matlab
@pytest.mark.parametrize(
    "lam",
    [0, 1, pytest.param(2, marks=_XFAIL_MULT), pytest.param(3, marks=_XFAIL_MULT)],
)
@pytest.mark.parametrize("n", [8, 12])
def test_ultras_multmat(n, lam):
    _assert_close(ultras.multmat(n, _MULT_COEFFS, lam), f"us_mult_n{n}_lam{lam}")


# ---------------------------------------------------------------------------
# trigcolloc: Fourier differentiation matrices (period 2 on [-1,1)).
#   m = 1..4 analytic (odd/even branches), m = 5 FFT eigenvalue branch.
# ---------------------------------------------------------------------------
@pytest.mark.matlab
@pytest.mark.parametrize("n", [7, 8, 9, 16])
@pytest.mark.parametrize("m", [1, 2, 3, 4, 5])
def test_trig_diffmat(n, m):
    _assert_close(trigcolloc.trig_diffmat(n, m), f"tc_diff_n{n}_m{m}")


# ---------------------------------------------------------------------------
# trigcolloc: equispaced points and trapezoidal quadrature weights.
# ---------------------------------------------------------------------------
@pytest.mark.matlab
@pytest.mark.parametrize("n", [7, 8, 16])
def test_trig_points(n):
    disc = TrigColloc(n=n, domain=Domain((-1.0, 1.0)))
    _assert_close(disc.points(), f"tc_pts_n{n}")


@pytest.mark.matlab
def test_trig_points_domain():
    disc = TrigColloc(n=8, domain=Domain((0.0, 2.0)))
    _assert_close(disc.points(), "tc_pts_n8_dom02")


@pytest.mark.matlab
@pytest.mark.parametrize("n", [8, 16])
def test_trig_weights(n):
    disc = TrigColloc(n=n, domain=Domain((-1.0, 1.0)))
    _assert_close(disc.weights(), f"tc_wts_n{n}")
