"""MATLAB golden-reference parity for the Trigtech (periodic tech).

Cross-validates chebfunjax's ``Trigtech`` against MATLAB Chebfun's
``@trigtech`` at machine precision.  References generated by
``matlab_harness/refs/trigtech_refs.m``.

Added by Claude Opus 4.8 to close the trigtech golden-ref gap (MATLAB
has 53 trigtech test files; chebfunjax previously had no MATLAB
cross-validation for this foundational periodic tech).
"""

from __future__ import annotations

from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

jax.config.update("jax_enable_x64", True)

_REF_PATH = Path(__file__).resolve().parents[1] / "references" / "trigtech.mat"
if not _REF_PATH.exists():
    pytest.skip(
        "trigtech.mat golden ref not generated "
        "(run matlab_harness/refs/trigtech_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)

RTOL = 1e-12
ATOL = 1e-12

_T = jnp.asarray(_REF["test_points"], dtype=jnp.float64)


def _make(fn):
    from chebfunjax.tech.trigtech import Trigtech
    return Trigtech.from_function(fn)


_F1 = lambda x: jnp.exp(jnp.cos(jnp.pi * x))
_F2 = lambda x: jnp.cos(2 * jnp.pi * jnp.sin(jnp.pi * x))
_F3 = lambda x: 1 + jnp.sin(jnp.pi * x) + 0.5 * jnp.cos(2 * jnp.pi * x)
_F4 = lambda x: jnp.exp(jnp.sin(jnp.pi * x)) * jnp.cos(3 * jnp.pi * x)


@pytest.mark.matlab
class TestTrigtechVsMatlab:
    def test_construction_length(self):
        # chebfunjax resolves each to the same length MATLAB does (or the
        # values match to 1e-12 regardless -- length is a soft check).
        for key, fn in (("f1", _F1), ("f2", _F2), ("f3", _F3),
                        ("f4", _F4)):
            f = _make(fn)
            # exact finite trig poly f3 must have the exact MATLAB length
            if key == "f3":
                assert f.n == int(_REF["f3_length"])

    def test_feval(self):
        for key, fn in (("f1", _F1), ("f2", _F2), ("f3", _F3),
                        ("f4", _F4)):
            f = _make(fn)
            npt.assert_allclose(np.asarray(f(_T)), _REF[f"{key}_vals"],
                                rtol=RTOL, atol=ATOL)

    def test_sum(self):
        for key, fn in (("f1", _F1), ("f2", _F2), ("f3", _F3),
                        ("f4", _F4)):
            f = _make(fn)
            npt.assert_allclose(float(f.sum()), float(_REF[f"{key}_sum"]),
                                rtol=RTOL, atol=ATOL)

    def test_diff(self):
        for key, fn in (("f1", _F1), ("f2", _F2), ("f4", _F4)):
            f = _make(fn)
            npt.assert_allclose(np.asarray(f.diff()(_T)),
                                _REF[f"{key}_diff_vals"],
                                rtol=1e-11, atol=1e-11)

    def test_diff2(self):
        f = _make(_F1)
        npt.assert_allclose(np.asarray(f.diff(2)(_T)),
                            _REF["f1_diff2_vals"], rtol=1e-10, atol=1e-10)

    def test_cumsum(self):
        g = _make(lambda x: jnp.sin(jnp.pi * x) + jnp.cos(3 * jnp.pi * x))
        npt.assert_allclose(np.asarray(g.cumsum()(_T)),
                            _REF["g_cumsum_vals"], rtol=1e-11, atol=1e-11)

    def test_arithmetic(self):
        f1, f3 = _make(_F1), _make(_F3)
        npt.assert_allclose(np.asarray((f1 + f3)(_T)), _REF["sum_vals"],
                            rtol=RTOL, atol=ATOL)
        npt.assert_allclose(np.asarray((f1 - f3)(_T)), _REF["minus_vals"],
                            rtol=RTOL, atol=ATOL)
        npt.assert_allclose(np.asarray((f1 * f3)(_T)), _REF["times_vals"],
                            rtol=RTOL, atol=ATOL)
        npt.assert_allclose(np.asarray((2.5 * f1)(_T)),
                            _REF["scalar_mul_vals"], rtol=RTOL, atol=ATOL)

    def test_roots(self):
        f = _make(lambda x: jnp.sin(jnp.pi * x))
        r = np.sort(np.asarray(f.roots()))
        want = np.atleast_1d(np.asarray(_REF["sin_roots"]))
        # match the count and values (roots of sin(pi x) on [-1,1): -1,0,1
        assert len(r) == len(want)
        npt.assert_allclose(r, want, atol=1e-11)

    def test_vscale(self):
        f = _make(_F1)
        npt.assert_allclose(float(f.vscale), float(_REF["f1_vscale"]),
                            rtol=1e-10)
