"""MATLAB golden-reference parity for Chebtech1 (Chebyshev 1st kind).

Cross-validates chebfunjax's Chebtech1 against MATLAB @chebtech1
(R2025b).  References generated by
``matlab_harness/refs/chebtech1_refs.m``.

Added by Claude Opus 4.8 (chebtech1 previously had no MATLAB golden
ref).
"""

from __future__ import annotations

from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

jax.config.update("jax_enable_x64", True)

from chebfunjax.tech.chebtech import Chebtech1  # noqa: E402

_REF_PATH = (
    Path(__file__).resolve().parents[1] / "references" / "chebtech1.mat"
)
if not _REF_PATH.exists():
    pytest.skip(
        "chebtech1.mat golden ref not generated "
        "(run matlab_harness/refs/chebtech1_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_XT = jnp.asarray(_REF["xt"], dtype=jnp.float64)


def _mk(fn):
    return Chebtech1.from_function(fn)


@pytest.mark.matlab
class TestChebtech1VsMatlab:
    def test_feval_sum(self):
        f = _mk(lambda x: jnp.exp(x) * jnp.sin(3 * x))
        npt.assert_allclose(np.asarray(f(_XT)), _REF["f_vals"],
                            rtol=1e-11, atol=1e-11)
        npt.assert_allclose(float(f.sum()), float(_REF["f_sum"]),
                            rtol=1e-11)

    def test_diff_cumsum(self):
        f = _mk(lambda x: jnp.exp(x) * jnp.sin(3 * x))
        npt.assert_allclose(np.asarray(f.diff()(_XT)), _REF["f_diff"],
                            rtol=1e-10, atol=1e-10)
        npt.assert_allclose(np.asarray(f.cumsum()(_XT)), _REF["f_cumsum"],
                            rtol=1e-10, atol=1e-10)

    def test_roots(self):
        g = _mk(lambda x: jnp.cos(5 * x))
        r = np.sort(np.asarray(g.roots()))
        want = np.sort(np.atleast_1d(np.asarray(_REF["g_roots"])))
        assert len(r) == len(want)
        npt.assert_allclose(r, want, atol=1e-11)

    def test_polynomial(self):
        p = _mk(lambda x: 1 + 2 * x + 3 * x ** 2)
        npt.assert_allclose(np.asarray(p(_XT)), _REF["p_vals"],
                            rtol=1e-12, atol=1e-12)
        npt.assert_allclose(float(p.sum()), float(_REF["p_sum"]),
                            rtol=1e-12)
