"""Expanded MATLAB golden-reference parity for Chebfun3.

Cross-validates chebfunjax's Chebfun3 against MATLAB @chebfun3
(R2025b): evaluation, triple integral, partial derivatives, Laplacian.
References generated by ``matlab_harness/refs/chebfun3_extras_refs.m``.

Added by Claude Opus 4.8.
"""

from __future__ import annotations

from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

jax.config.update("jax_enable_x64", True)

from chebfunjax.chebfun3d.chebfun3 import Chebfun3  # noqa: E402

_REF_PATH = (
    Path(__file__).resolve().parents[1] / "references" / "chebfun3_extras.mat"
)
if not _REF_PATH.exists():
    pytest.skip(
        "chebfun3_extras.mat golden ref not generated "
        "(run matlab_harness/refs/chebfun3_extras_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_P = np.atleast_2d(np.asarray(_REF["P"]))
_XX = jnp.asarray(_P[:, 0], dtype=jnp.float64)
_YY = jnp.asarray(_P[:, 1], dtype=jnp.float64)
_ZZ = jnp.asarray(_P[:, 2], dtype=jnp.float64)

_DOM = (-1.0, 1.0, -1.0, 1.0, -1.0, 1.0)


def _mk(fn):
    return Chebfun3.from_function(fn, domain=_DOM)


@pytest.mark.matlab
class TestChebfun3ExtrasVsMatlab:
    def test_f_eval_and_partials(self):
        """f = exp(x) sin(y) cos(z): eval, sum3, d/dx, d/dy, d/dz."""
        f = _mk(lambda x, y, z: jnp.exp(x) * jnp.sin(y) * jnp.cos(z))
        npt.assert_allclose(np.asarray(f(_XX, _YY, _ZZ)), _REF["f_eval"],
                            rtol=1e-11, atol=1e-11)
        # sum3 = 0 exactly (sin(y) odd); compare with atol
        npt.assert_allclose(float(f.sum3()), float(_REF["f_sum3"]),
                            rtol=1e-10, atol=1e-12)
        npt.assert_allclose(np.asarray(f.diff(1)(_XX, _YY, _ZZ)),
                            _REF["f_dx"], rtol=1e-9, atol=1e-9)
        npt.assert_allclose(np.asarray(f.diff(2)(_XX, _YY, _ZZ)),
                            _REF["f_dy"], rtol=1e-9, atol=1e-9)
        npt.assert_allclose(np.asarray(f.diff(3)(_XX, _YY, _ZZ)),
                            _REF["f_dz"], rtol=1e-9, atol=1e-9)

    def test_g_eval_sum_laplacian(self):
        """g = x^2+y^2+z^2: eval, triple integral, Laplacian == 6."""
        g = _mk(lambda x, y, z: x ** 2 + y ** 2 + z ** 2)
        npt.assert_allclose(np.asarray(g(_XX, _YY, _ZZ)), _REF["g_eval"],
                            rtol=1e-11, atol=1e-11)
        npt.assert_allclose(float(g.sum3()), float(_REF["g_sum3"]),
                            rtol=1e-11)
        lap = (np.asarray(g.diff(1, 2)(_XX, _YY, _ZZ))
               + np.asarray(g.diff(2, 2)(_XX, _YY, _ZZ))
               + np.asarray(g.diff(3, 2)(_XX, _YY, _ZZ)))
        npt.assert_allclose(lap, _REF["g_lap"], atol=1e-8)
        npt.assert_allclose(lap, 6.0 * np.ones_like(lap), atol=1e-7)
