"""MATLAB golden-reference parity tests for the chebfun3d (Chebfun3) module.

Pins evaluation, sum3 (triple integral), and the trilinear (Tucker) rank
against MATLAB Chebfun3 (default ``chebfun3f`` constructor) at rtol 1e-12.
Golden ref generated by matlab_harness/refs/chebfun3_refs.m
(-> tests/references/chebfun3.mat).

MATLAB coordinate/eval convention matches chebfunjax's native one:
``chebfun3(@(x,y,z) ...)`` with element-wise ``feval(f, x, y, z)`` on matched
point vectors, exactly like ``Chebfun3.__call__`` (broadcasting, element-wise).

Note: MATLAB ``norm(chebfun3)`` (Frobenius) is stored in the ``.mat`` for
forward-compatibility, but chebfunjax's ``Chebfun3`` does not yet expose a
``norm()`` method, so that assertion is skipped (see ``test_norm``).
"""

from pathlib import Path

import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

from chebfunjax.chebfun3d.chebfun3 import chebfun3

_REF_PATH = Path(__file__).resolve().parents[1] / "references" / "chebfun3.mat"
if not _REF_PATH.exists():
    pytest.skip(
        "chebfun3.mat golden ref not generated "
        "(run matlab_harness/refs/chebfun3_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_PX = jnp.asarray(_REF["pts_x"], dtype=jnp.float64)
_PY = jnp.asarray(_REF["pts_y"], dtype=jnp.float64)
_PZ = jnp.asarray(_REF["pts_z"], dtype=jnp.float64)
_QX = jnp.asarray(_REF["qx"], dtype=jnp.float64)
_QY = jnp.asarray(_REF["qy"], dtype=jnp.float64)
_QZ = jnp.asarray(_REF["qz"], dtype=jnp.float64)

# Same battery as matlab_harness/refs/chebfun3_refs.m, on the default domain.
_FUNS = {
    1: lambda x, y, z: jnp.cos(x) * jnp.sin(y) * jnp.exp(z),
    2: lambda x, y, z: 1.0 / (1.0 + x**2 + y**2 + z**2),
    3: lambda x, y, z: x**2 - y**2 + z * x,
    4: lambda x, y, z: jnp.exp(x * y * z),
}

RTOL = 1e-12


@pytest.mark.matlab
@pytest.mark.parametrize("i", [1, 2, 3, 4])
class TestChebfun3VsMatlab:
    def test_eval(self, i):
        f = chebfun3(_FUNS[i])
        got = np.asarray(f(_PX, _PY, _PZ))
        npt.assert_allclose(got, _REF[f"f{i}_eval"], rtol=RTOL, atol=1e-13)

    def test_sum3(self, i):
        f = chebfun3(_FUNS[i])
        npt.assert_allclose(float(f.sum3()), float(_REF[f"f{i}_sum3"]),
                            rtol=RTOL, atol=1e-12)

    def test_rank(self, i):
        # chebfunjax f.rank == (rx, ry, rz) == MATLAB [rX, rY, rZ] = rank(f)
        # (both are the size of the Tucker core built by chebfun3f).
        f = chebfun3(_FUNS[i])
        got = tuple(int(v) for v in f.rank)
        expected = tuple(int(v) for v in np.atleast_1d(_REF[f"f{i}_rank"]))
        assert got == expected

    def test_norm(self, i):
        # MATLAB norm(f) (Frobenius) is pinned in chebfun3.mat, but chebfunjax
        # Chebfun3 exposes no norm() yet.  Skip until the method lands, then
        # assert float(f.norm()) == _REF[f"f{i}_norm"] at rtol 1e-12.
        f = chebfun3(_FUNS[i])
        if not hasattr(f, "norm"):
            pytest.skip("Chebfun3.norm() (Frobenius) not implemented in chebfunjax")
        npt.assert_allclose(float(f.norm()), float(_REF[f"f{i}_norm"]), rtol=RTOL)


@pytest.mark.matlab
class TestChebfun3NonUnitDomain:
    def _g(self):
        return chebfun3(lambda x, y, z: jnp.sin(2 * x) + jnp.cos(y) + x * z,
                        domain=tuple(float(v) for v in _REF["dom"]))

    def test_eval(self):
        npt.assert_allclose(np.asarray(self._g()(_QX, _QY, _QZ)), _REF["g_eval"],
                            rtol=RTOL, atol=1e-13)

    def test_sum3(self):
        npt.assert_allclose(float(self._g().sum3()), float(_REF["g_sum3"]),
                            rtol=RTOL, atol=1e-12)

    def test_rank(self):
        got = tuple(int(v) for v in self._g().rank)
        expected = tuple(int(v) for v in np.atleast_1d(_REF["g_rank"]))
        assert got == expected

    def test_norm(self):
        g = self._g()
        if not hasattr(g, "norm"):
            pytest.skip("Chebfun3.norm() (Frobenius) not implemented in chebfunjax")
        npt.assert_allclose(float(g.norm()), float(_REF["g_norm"]), rtol=RTOL)
