"""MATLAB golden-reference parity for additional Chebop operations.

Extends the operators parity suite with variable-coefficient, Neumann,
and eigenvalue problems, cross-validated against MATLAB @chebop
(R2025b).  References generated by
``matlab_harness/refs/chebop_extras_refs.m``.

Added by Claude Opus 4.8 to broaden chebop cross-validation (MATLAB has
99 chebop test files; only a handful of BVPs were previously pinned).
"""

from __future__ import annotations

from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

jax.config.update("jax_enable_x64", True)

from chebfunjax.operators.chebop import Chebop  # noqa: E402

_REF_PATH = (
    Path(__file__).resolve().parents[1] / "references" / "chebop_extras.mat"
)
if not _REF_PATH.exists():
    pytest.skip(
        "chebop_extras.mat golden ref not generated "
        "(run matlab_harness/refs/chebop_extras_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_PTS = jnp.asarray(_REF["pts"], dtype=jnp.float64)


@pytest.mark.matlab
class TestChebopExtrasVsMatlab:
    def test_varcoeff_bvp(self):
        """u'' + x u = 1, u(-1)=u(1)=0."""
        L = Chebop(lambda x, u: u.diff(2) + x * u, domain=(-1.0, 1.0))
        L.lbc = 0.0
        L.rbc = 0.0
        u = L.solve(1.0)
        npt.assert_allclose(np.asarray(u(_PTS)), _REF["varcoeff_vals"],
                            rtol=1e-10, atol=1e-11)

    def test_neumann_bvp(self):
        """u'' - u = 1, u'(-1)=0, u(1)=0."""
        L = Chebop(lambda x, u: u.diff(2) - u, domain=(-1.0, 1.0))
        L.lbc = lambda u: u.diff()
        L.rbc = 0.0
        u = L.solve(1.0)
        npt.assert_allclose(np.asarray(u(_PTS)), _REF["neumann_vals"],
                            rtol=1e-10, atol=1e-11)

    def test_varcoeff2_bvp(self):
        """u'' + sin(pi x) u = cos(pi x), Dirichlet."""
        L = Chebop(lambda x, u: u.diff(2) + (jnp.pi * x).sin() * u,
                   domain=(-1.0, 1.0))
        L.lbc = 0.0
        L.rbc = 0.0
        u = L.solve(lambda x: jnp.cos(jnp.pi * x))
        npt.assert_allclose(np.asarray(u(_PTS)), _REF["varcoeff2_vals"],
                            rtol=1e-10, atol=1e-11)

    def test_harmonic_oscillator_eigs(self):
        """-u'' + x^2 u = lam u on [-6,6]; exact eigenvalues 1,3,5,7,9."""
        L = Chebop(lambda x, u: -u.diff(2) + x ** 2 * u,
                   domain=(-6.0, 6.0))
        L.bc = 0.0
        got = np.sort(np.real(np.asarray(L.eigs(k=5))))
        want = np.sort(np.atleast_1d(np.asarray(_REF["harmonic_eigs"])))
        npt.assert_allclose(got, want, rtol=1e-8, atol=1e-8)
        # also matches the analytic spectrum
        npt.assert_allclose(got, [1, 3, 5, 7, 9], rtol=1e-6, atol=1e-6)

    def test_laplacian01_eigs(self):
        """-u'' on [0,1] Dirichlet; exact eigenvalues (pi n)^2."""
        L = Chebop(lambda x, u: -u.diff(2), domain=(0.0, 1.0))
        L.bc = 0.0
        got = np.sort(np.real(np.asarray(L.eigs(k=6))))
        want = np.sort(np.atleast_1d(np.asarray(_REF["laplacian01_eigs"])))
        npt.assert_allclose(got, want, rtol=1e-8, atol=1e-7)
        npt.assert_allclose(got, [(np.pi * n) ** 2 for n in range(1, 7)],
                            rtol=1e-6)


@pytest.mark.parametrize("_dummy", [0])
class TestChebopPeriodic:
    """Periodic BVPs via Fourier collocation (Opus 4.8, task #24).

    No MATLAB ref needed -- verified against exact solutions and by
    substituting the solution back into the operator (residual check).
    """

    def test_constant_coeff(self, _dummy):
        # u'' - u = cos(2x) on [-pi,pi] periodic -> u = -cos(2x)/5
        L = Chebop(lambda x, u: u.diff(2) - u, domain=(-np.pi, np.pi))
        L.bc = "periodic"
        u = L.solve(lambda x: jnp.cos(2 * x))
        xs = np.linspace(-3.0, 3.0, 60)
        npt.assert_allclose(np.asarray(u(jnp.asarray(xs))),
                            -np.cos(2 * xs) / 5, atol=1e-10)

    def test_variable_coeff_residual(self, _dummy):
        # u'' + u' + (2+sin x) u = 1 ; check by residual
        L = Chebop(lambda x, u: u.diff(2) + u.diff() + (2 + jnp.sin(x)) * u,
                   domain=(-np.pi, np.pi))
        L.bc = "periodic"
        u = L.solve(1.0)
        xs = np.linspace(-3.0, 3.0, 60)
        uu = np.asarray(u(jnp.asarray(xs)))
        du = np.asarray(u.diff()(jnp.asarray(xs)))
        d2u = np.asarray(u.diff().diff()(jnp.asarray(xs)))
        residual = d2u + du + (2 + np.sin(xs)) * uu
        npt.assert_allclose(residual, np.ones_like(residual), atol=1e-9)
