"""Second batch of Chebop MATLAB golden-reference parity.

Cross-validates a Mathieu eigenvalue problem, an Airy-type oscillatory
BVP, and a cosine-coefficient BVP against MATLAB @chebop (R2025b).
References generated by ``matlab_harness/refs/chebop2_refs.m``.

Added by Claude Opus 4.8.
"""

from __future__ import annotations

from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

jax.config.update("jax_enable_x64", True)

from chebfunjax.operators.chebop import Chebop  # noqa: E402

_REF_PATH = (
    Path(__file__).resolve().parents[1] / "references" / "chebop2.mat"
)
if not _REF_PATH.exists():
    pytest.skip(
        "chebop2.mat golden ref not generated "
        "(run matlab_harness/refs/chebop2_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_PTS1 = jnp.asarray(_REF["pts1"], dtype=jnp.float64)


@pytest.mark.matlab
class TestChebop2VsMatlab:
    def test_mathieu_eigs(self):
        L = Chebop(lambda x, u: -u.diff(2) + 4 * (2 * x).cos() * u,
                   domain=(0.0, np.pi))
        L.bc = 0.0
        got = np.sort(np.real(np.asarray(L.eigs(k=4))))
        want = np.sort(np.atleast_1d(np.asarray(_REF["mathieu_eigs"])))
        npt.assert_allclose(got, want, rtol=1e-7, atol=1e-7)

    def test_airy_bvp(self):
        L = Chebop(lambda x, u: u.diff(2) - 30 * x * u,
                   domain=(-1.0, 1.0))
        L.lbc = 1.0
        L.rbc = 0.0
        u = L.solve(0.0)
        npt.assert_allclose(np.asarray(u(_PTS1)), _REF["airy_vals"],
                            rtol=1e-9, atol=1e-10)

    def test_cosine_coeff_bvp(self):
        L = Chebop(lambda x, u: u.diff(2) + (jnp.pi * x).cos() * u,
                   domain=(-1.0, 1.0))
        L.lbc = 0.0
        L.rbc = 0.0
        u = L.solve(1.0)
        npt.assert_allclose(np.asarray(u(_PTS1)), _REF["cosbvp_vals"],
                            rtol=1e-9, atol=1e-10)
