"""Nonlinear Chebop BVP MATLAB golden-reference parity (2nd batch).

Cross-validates chebfunjax's damped-Newton Chebop.solve against MATLAB
@chebop (R2025b) on the Bratu equation (lower branch) and a monotone
sinh-reaction BVP.  References generated by
``matlab_harness/refs/chebop_nonlinear2_refs.m``.

Added by Claude Opus 4.8.
"""

from __future__ import annotations

from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

jax.config.update("jax_enable_x64", True)

from chebfunjax.operators.chebop import Chebop  # noqa: E402

_REF_PATH = (
    Path(__file__).resolve().parents[1] / "references"
    / "chebop_nonlinear2.mat"
)
if not _REF_PATH.exists():
    pytest.skip(
        "chebop_nonlinear2.mat golden ref not generated "
        "(run matlab_harness/refs/chebop_nonlinear2_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_PTS = jnp.asarray(_REF["pts"], dtype=jnp.float64)
_PTS2 = jnp.asarray(_REF["pts2"], dtype=jnp.float64)


@pytest.mark.matlab
class TestChebopNonlinear2VsMatlab:
    def test_bratu(self):
        """u'' + exp(u) = 0, u(0)=u(1)=0 (lower branch)."""
        L = Chebop(lambda x, u: u.diff(2) + u.exp(), domain=(0.0, 1.0))
        L.lbc = 0.0
        L.rbc = 0.0
        u = L.solve(0.0)
        npt.assert_allclose(np.asarray(u(_PTS)), _REF["bratu_vals"],
                            rtol=1e-8, atol=1e-9)

    def test_sinh_reaction(self):
        """u'' - sinh(u) = x, u(-1)=u(1)=0 (monotone, unique)."""
        L = Chebop(lambda x, u: u.diff(2) - u.sinh(), domain=(-1.0, 1.0))
        L.lbc = 0.0
        L.rbc = 0.0
        u = L.solve(lambda x: x)
        npt.assert_allclose(np.asarray(u(_PTS2)), _REF["sinh_vals"],
                            rtol=1e-8, atol=1e-9)
