"""MATLAB golden-reference parity tests for the chebfun3d vector module (Chebfun3v).

Pins the available 3D vector operations against MATLAB Chebfun3v at rtol 1e-12:
component evaluation, dot, cross, and the pointwise Euclidean magnitude.
Golden ref generated by matlab_harness/refs/chebfun3v_refs.m
(-> tests/references/chebfun3v.mat).  Cartesian on [-1,1]^3, element-wise eval.

NOTE: chebfunjax Chebfun3v.norm() returns the POINTWISE magnitude
sqrt(f^2+g^2+h^2) as a Chebfun3, whereas MATLAB @chebfun3v/norm returns the
Frobenius SCALAR.  We pin the pointwise field (what chebfunjax computes); the
MATLAB Frobenius scalar is stored as normF_frob for documentation only.
"""

from pathlib import Path

import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

from chebfunjax.chebfun3d.chebfun3v import Chebfun3v

_REF_PATH = Path(__file__).resolve().parents[1] / "references" / "chebfun3v.mat"
if not _REF_PATH.exists():
    pytest.skip(
        "chebfun3v.mat golden ref not generated "
        "(run matlab_harness/refs/chebfun3v_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_PX = jnp.asarray(_REF["pts_x"], dtype=jnp.float64)
_PY = jnp.asarray(_REF["pts_y"], dtype=jnp.float64)
_PZ = jnp.asarray(_REF["pts_z"], dtype=jnp.float64)

RTOL = 1e-12


def _F():
    return Chebfun3v.from_functions(
        lambda x, y, z: jnp.cos(x) * jnp.sin(y),
        lambda x, y, z: jnp.exp(z),
        lambda x, y, z: x * y,
    )


def _G():
    return Chebfun3v.from_functions(
        lambda x, y, z: x * z,
        lambda x, y, z: y,
        lambda x, y, z: z**2,
    )


@pytest.mark.matlab
class TestChebfun3vVsMatlab:
    def test_component_eval(self):
        f, g, h = (np.asarray(v) for v in _F()(_PX, _PY, _PZ))
        npt.assert_allclose(f, _REF["F1_eval"], rtol=RTOL, atol=1e-13)
        npt.assert_allclose(g, _REF["F2_eval"], rtol=RTOL, atol=1e-13)
        npt.assert_allclose(h, _REF["F3_eval"], rtol=RTOL, atol=1e-13)

    def test_dot(self):
        d = _F().dot(_G())
        npt.assert_allclose(np.asarray(d(_PX, _PY, _PZ)), _REF["dot_eval"],
                            rtol=RTOL, atol=1e-13)

    def test_cross(self):
        cx, cy, cz = (np.asarray(v) for v in _F().cross(_G())(_PX, _PY, _PZ))
        npt.assert_allclose(cx, _REF["crossx_eval"], rtol=RTOL, atol=1e-13)
        npt.assert_allclose(cy, _REF["crossy_eval"], rtol=RTOL, atol=1e-13)
        npt.assert_allclose(cz, _REF["crossz_eval"], rtol=RTOL, atol=1e-13)

    def test_norm_pointwise(self):
        # Chebfun3v.norm() returns the pointwise magnitude field sqrt(sum comp^2).
        n = _F().norm()
        npt.assert_allclose(np.asarray(n(_PX, _PY, _PZ)), _REF["normP_eval"],
                            rtol=RTOL, atol=1e-12)
