"""MATLAB golden-reference parity for Chebfun2v / Chebfun3v vector fields.

Cross-validates chebfunjax's vector-field calculus (2v: div, curl, dot,
cross; 3v: dot, cross) against MATLAB @chebfun2v / @chebfun3v (R2025b).
References generated by ``matlab_harness/refs/chebfunv_refs.m``.

Added by Claude Opus 4.8.
"""

from __future__ import annotations

from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

jax.config.update("jax_enable_x64", True)

from chebfunjax.chebfun2d.chebfun2v import Chebfun2v  # noqa: E402
from chebfunjax.chebfun3d.chebfun3v import Chebfun3v  # noqa: E402

_REF_PATH = (
    Path(__file__).resolve().parents[1] / "references" / "chebfunv.mat"
)
if not _REF_PATH.exists():
    pytest.skip(
        "chebfunv.mat golden ref not generated "
        "(run matlab_harness/refs/chebfunv_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_X = jnp.asarray(_REF["X"], dtype=jnp.float64)
_Y = jnp.asarray(_REF["Y"], dtype=jnp.float64)
_P = np.atleast_2d(np.asarray(_REF["P"]))
_XX = jnp.asarray(_P[:, 0], dtype=jnp.float64)
_YY = jnp.asarray(_P[:, 1], dtype=jnp.float64)
_ZZ = jnp.asarray(_P[:, 2], dtype=jnp.float64)

_D2 = (-1.0, 1.0, -1.0, 1.0)
_D3 = (-1.0, 1.0, -1.0, 1.0, -1.0, 1.0)


@pytest.mark.matlab
class TestChebfun2vVsMatlab:
    def _F(self):
        return Chebfun2v.from_functions(
            lambda x, y: x ** 2 * y, lambda x, y: jnp.sin(x) * y, domain=_D2)

    def _G(self):
        return Chebfun2v.from_functions(
            lambda x, y: y, lambda x, y: x, domain=_D2)

    def test_divergence(self):
        d = self._F().div()
        npt.assert_allclose(np.asarray(d(_X, _Y)), _REF["f2v_div"],
                            rtol=1e-9, atol=1e-9)

    def test_curl(self):
        c = self._F().curl()
        npt.assert_allclose(np.asarray(c(_X, _Y)), _REF["f2v_curl"],
                            rtol=1e-9, atol=1e-9)

    def test_dot(self):
        d = self._F().dot(self._G())
        npt.assert_allclose(np.asarray(d(_X, _Y)), _REF["f2v_dot"],
                            rtol=1e-10, atol=1e-10)

    def test_cross(self):
        c = self._F().cross(self._G())
        npt.assert_allclose(np.asarray(c(_X, _Y)), _REF["f2v_cross"],
                            rtol=1e-10, atol=1e-10)


@pytest.mark.matlab
class TestChebfun3vVsMatlab:
    def _H(self):
        return Chebfun3v.from_functions(
            lambda x, y, z: x * y, lambda x, y, z: y * z,
            lambda x, y, z: x * z, domain=_D3)

    def _K(self):
        return Chebfun3v.from_functions(
            lambda x, y, z: z, lambda x, y, z: x, lambda x, y, z: y,
            domain=_D3)

    def test_dot(self):
        d = self._H().dot(self._K())
        npt.assert_allclose(np.asarray(d(_XX, _YY, _ZZ)), _REF["f3v_dot"],
                            rtol=1e-10, atol=1e-10)

    def test_cross(self):
        c = self._H().cross(self._K())
        comps = [c[i] if hasattr(c, "__getitem__") else None
                 for i in range(3)]
        # fall back to component accessor names if indexing unsupported
        if comps[0] is None:
            comps = [c.components[i] for i in range(3)]
        for i, key in enumerate(
                ("f3v_cross1", "f3v_cross2", "f3v_cross3")):
            npt.assert_allclose(np.asarray(comps[i](_XX, _YY, _ZZ)),
                                _REF[key], rtol=1e-10, atol=1e-10)
