"""MATLAB golden-reference parity tests for the chebfun2d vector module (Chebfun2v).

Pins the 2D vector-calculus operations against MATLAB Chebfun2v at rtol 1e-12:
component evaluation, divergence, curl (2D scalar), dot, cross (2D scalar),
Frobenius norm (scalar), and the scalar gradient [f_x; f_y].  Golden ref
generated by matlab_harness/refs/chebfun2v_refs.m (-> tests/references/chebfun2v.mat).

Coordinate convention matches MATLAB: Cartesian on [xa,xb]x[ya,yb], component
functions f(x,y), g(x,y), element-wise eval.  MATLAB diff(.,1,2) = d/dx and
diff(.,1,1) = d/dy, matching chebfunjax Chebfun2.diff(dim=2)=d/dx, diff(dim=1)=d/dy.
"""

from pathlib import Path

import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

import chebfunjax as cj
from chebfunjax.chebfun2d.chebfun2v import Chebfun2v

_REF_PATH = Path(__file__).resolve().parents[1] / "references" / "chebfun2v.mat"
if not _REF_PATH.exists():
    pytest.skip(
        "chebfun2v.mat golden ref not generated "
        "(run matlab_harness/refs/chebfun2v_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_PX = jnp.asarray(_REF["pts_x"], dtype=jnp.float64)
_PY = jnp.asarray(_REF["pts_y"], dtype=jnp.float64)
_QX = jnp.asarray(_REF["qx"], dtype=jnp.float64)
_QY = jnp.asarray(_REF["qy"], dtype=jnp.float64)
_DOM = tuple(float(v) for v in _REF["dom"])

RTOL = 1e-12


def _F():
    return Chebfun2v.from_functions(
        lambda x, y: jnp.cos(x) * jnp.sin(y),
        lambda x, y: jnp.exp(x + y),
    )


def _G():
    return Chebfun2v.from_functions(
        lambda x, y: x**2 - y,
        lambda x, y: x * y,
    )


@pytest.mark.matlab
class TestChebfun2vVsMatlab:
    def test_component_eval(self):
        F = _F()
        vals = np.asarray(F(_PX, _PY))  # shape (m, 2)
        npt.assert_allclose(vals[:, 0], _REF["F1_eval"], rtol=RTOL, atol=1e-13)
        npt.assert_allclose(vals[:, 1], _REF["F2_eval"], rtol=RTOL, atol=1e-13)

    def test_component_eval_G(self):
        G = _G()
        vals = np.asarray(G(_PX, _PY))
        npt.assert_allclose(vals[:, 0], _REF["G1_eval"], rtol=RTOL, atol=1e-13)
        npt.assert_allclose(vals[:, 1], _REF["G2_eval"], rtol=RTOL, atol=1e-13)

    def test_divergence(self):
        div = _F().divergence()
        npt.assert_allclose(np.asarray(div(_PX, _PY)), _REF["div_eval"],
                            rtol=RTOL, atol=1e-13)

    def test_curl(self):
        curl = _F().curl()
        npt.assert_allclose(np.asarray(curl(_PX, _PY)), _REF["curl_eval"],
                            rtol=RTOL, atol=1e-13)

    def test_dot(self):
        d = _F().dot(_G())
        npt.assert_allclose(np.asarray(d(_PX, _PY)), _REF["dot_eval"],
                            rtol=RTOL, atol=1e-13)

    def test_cross(self):
        c = _F().cross(_G())
        npt.assert_allclose(np.asarray(c(_PX, _PY)), _REF["cross_eval"],
                            rtol=RTOL, atol=1e-13)

    def test_norm_frobenius(self):
        # Chebfun2v.norm() is the Frobenius scalar, matching MATLAB norm(F).
        npt.assert_allclose(float(_F().norm()), float(_REF["normF"]), rtol=RTOL)

    def test_gradient_components(self):
        # Scalar gradient of f = cos(x)sin(y): grad(f) = [f_x; f_y].
        # chebfunjax has no Chebfun2.gradient() convenience method, so the
        # components are obtained via diff: dim=2 -> d/dx, dim=1 -> d/dy.
        f = cj.chebfun2(lambda x, y: jnp.cos(x) * jnp.sin(y))
        fx = f.diff(dim=2)  # d/dx
        fy = f.diff(dim=1)  # d/dy
        npt.assert_allclose(np.asarray(fx(_PX, _PY)), _REF["gradx_eval"],
                            rtol=RTOL, atol=1e-13)
        npt.assert_allclose(np.asarray(fy(_PX, _PY)), _REF["grady_eval"],
                            rtol=RTOL, atol=1e-13)


@pytest.mark.matlab
class TestChebfun2vNonUnitDomain:
    def _H(self):
        return Chebfun2v.from_functions(
            lambda x, y: jnp.sin(3 * x) + jnp.cos(2 * y),
            lambda x, y: x * y - y**2,
            domain=_DOM,
        )

    def test_divergence(self):
        div = self._H().divergence()
        npt.assert_allclose(np.asarray(div(_QX, _QY)), _REF["div2_eval"],
                            rtol=RTOL, atol=1e-13)

    def test_curl(self):
        curl = self._H().curl()
        npt.assert_allclose(np.asarray(curl(_QX, _QY)), _REF["curl2_eval"],
                            rtol=RTOL, atol=1e-13)
