"""MATLAB golden-reference parity tests for the spherefun vector module (Spherefunv).

Pins chebfunjax Spherefunv operations against MATLAB SPHEREFUN (scalar)
construction at rtol 1e-12: component evaluation, dot, and the pointwise
Euclidean magnitude.  Golden ref generated by
matlab_harness/refs/spherefunv_refs.m (-> tests/references/spherefunv.mat).

IMPORTANT CONVENTION GAP:  MATLAB @spherefunv is intrinsically a 3-component
(Cartesian x,y,z) tangent vector field, while chebfunjax Spherefunv is a thin
2-component wrapper [f(lam,theta); g(lam,theta)] whose dot/norm are plain
scalar-field algebra.  The two classes are NOT directly comparable, so the
golden refs are built from MATLAB spherefun (scalar) composites of the same
formulas.  This validates that the chebfunjax wrapper composes the scalar
spherefun ops correctly; it does not test MATLAB @spherefunv.

Convention: spherical-native f(lam, theta), lam in [-pi,pi], theta in [0,pi].
Spherefunv.norm() returns the POINTWISE magnitude sqrt(f^2+g^2) as a Spherefun.
"""

from pathlib import Path

import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

from chebfunjax.spherefun.spherefunv import Spherefunv

_REF_PATH = Path(__file__).resolve().parents[1] / "references" / "spherefunv.mat"
if not _REF_PATH.exists():
    pytest.skip(
        "spherefunv.mat golden ref not generated "
        "(run matlab_harness/refs/spherefunv_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_LAM = jnp.asarray(_REF["lam"], dtype=jnp.float64)
_TH = jnp.asarray(_REF["th"], dtype=jnp.float64)

RTOL = 1e-12


def _F():
    return Spherefunv.from_functions(
        lambda lam, th: jnp.sin(th) * jnp.cos(lam),   # x
        lambda lam, th: jnp.cos(th),                  # z
    )


def _G():
    return Spherefunv.from_functions(
        lambda lam, th: jnp.sin(th) * jnp.sin(lam),   # y
        lambda lam, th: jnp.sin(th) * jnp.cos(lam),   # x
    )


def _N():
    # Field bounded away from 0: [2+x, z] — smooth magnitude, resolvable.
    return Spherefunv.from_functions(
        lambda lam, th: 2.0 + jnp.sin(th) * jnp.cos(lam),
        lambda lam, th: jnp.cos(th),
    )


@pytest.mark.matlab
class TestSpherefunvVsMatlab:
    def test_component_eval(self):
        f_val, g_val = _F()(_LAM, _TH)
        npt.assert_allclose(np.asarray(f_val), _REF["F1_eval"], rtol=RTOL, atol=1e-12)
        npt.assert_allclose(np.asarray(g_val), _REF["F2_eval"], rtol=RTOL, atol=1e-12)

    def test_dot(self):
        d = _F().dot(_G())
        npt.assert_allclose(np.asarray(d(_LAM, _TH)), _REF["dot_eval"],
                            rtol=RTOL, atol=1e-12)

    def test_norm_pointwise(self):
        # Spherefunv.norm() returns the pointwise magnitude field sqrt(f^2+g^2).
        n = _N().norm()
        npt.assert_allclose(np.asarray(n(_LAM, _TH)), _REF["norm_eval"],
                            rtol=RTOL, atol=1e-12)
