"""MATLAB golden-reference parity for Singfun and Deltafun.

Standalone cross-validation of the two Layer-3 "generalized function"
classes against MATLAB Chebfun (@singfun, @deltafun, R2025b).  MATLAB
has 24 singfun + 19 deltafun test files; chebfunjax previously
exercised these only thinly via the fun-layer ref.  References
generated by ``matlab_harness/refs/fun_singdelta_refs.m``.

Added by Claude Opus 4.8.
"""

from __future__ import annotations

from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

jax.config.update("jax_enable_x64", True)

from chebfunjax.domain import Domain  # noqa: E402
from chebfunjax.fun.bndfun import Bndfun  # noqa: E402
from chebfunjax.fun.deltafun import Deltafun  # noqa: E402
from chebfunjax.fun.singfun import Singfun  # noqa: E402

_REF_PATH = (
    Path(__file__).resolve().parents[1] / "references" / "fun_singdelta.mat"
)
if not _REF_PATH.exists():
    pytest.skip(
        "fun_singdelta.mat golden ref not generated "
        "(run matlab_harness/refs/fun_singdelta_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_PTS = jnp.asarray(_REF["pts"], dtype=jnp.float64)


@pytest.mark.matlab
class TestSingfunVsMatlab:
    def test_s1(self):
        """(1-x)^(-1/2) cos(x), exponents [0, -1/2]."""
        s = Singfun.from_function(
            lambda x: (1 - x) ** (-0.5) * jnp.cos(x), exponents=(0.0, -0.5))
        npt.assert_allclose(np.asarray(s(_PTS)), _REF["s1_vals"],
                            rtol=1e-11, atol=1e-11)
        npt.assert_allclose(float(s.sum()), float(_REF["s1_sum"]),
                            rtol=1e-10)

    def test_s2(self):
        """(1+x)^(1/2) exp(x), exponents [1/2, 0]."""
        s = Singfun.from_function(
            lambda x: (1 + x) ** (0.5) * jnp.exp(x), exponents=(0.5, 0.0))
        npt.assert_allclose(np.asarray(s(_PTS)), _REF["s2_vals"],
                            rtol=1e-11, atol=1e-11)
        npt.assert_allclose(float(s.sum()), float(_REF["s2_sum"]),
                            rtol=1e-10)
        npt.assert_allclose(np.asarray(s.diff()(_PTS)),
                            _REF["s2_diff_vals"], rtol=1e-9, atol=1e-9)

    def test_s3_arcsine_weight(self):
        """1/sqrt(1-x^2), exponents [-1/2, -1/2]; sum = pi."""
        s = Singfun.from_function(
            lambda x: (1 + x) ** (-0.5) * (1 - x) ** (-0.5),
            exponents=(-0.5, -0.5))
        npt.assert_allclose(np.asarray(s(_PTS)), _REF["s3_vals"],
                            rtol=1e-11, atol=1e-11)
        npt.assert_allclose(float(s.sum()), float(_REF["s3_sum"]),
                            rtol=1e-10)
        npt.assert_allclose(float(s.sum()), np.pi, rtol=1e-9)


def _smooth(fn):
    return Bndfun.from_function(fn, domain=Domain((-1.0, 1.0)))


@pytest.mark.matlab
class TestDeltafunVsMatlab:
    def test_d1_sum_and_smooth(self):
        """exp(x) + 2*delta(x-0.5): sum and away-from-delta values."""
        d = Deltafun.from_fun_and_deltas(_smooth(jnp.exp), [0.5], [2.0])
        npt.assert_allclose(float(d.sum()), float(_REF["d1_sum"]),
                            rtol=1e-11)
        npt.assert_allclose(np.asarray(d(_PTS)), _REF["d1_smooth_vals"],
                            rtol=1e-11, atol=1e-11)

    def test_d2_sum(self):
        """exp(x) + 1.5*delta(x+0.4) - 0.5*delta(x-0.6)."""
        d = Deltafun.from_fun_and_deltas(
            _smooth(jnp.exp), [-0.4, 0.6], [1.5, -0.5])
        npt.assert_allclose(float(d.sum()), float(_REF["d2_sum"]),
                            rtol=1e-11)

    def test_d3_sum(self):
        """sin(3x) + three unit deltas; sum = 0 + 3."""
        d = Deltafun.from_fun_and_deltas(
            _smooth(lambda x: jnp.sin(3 * x)),
            [-0.5, 0.0, 0.5], [1.0, 1.0, 1.0])
        npt.assert_allclose(float(d.sum()), float(_REF["d3_sum"]),
                            rtol=1e-10, atol=1e-11)
