"""MATLAB golden-ref parity for the Ballfun calculus operations.

Pins diff (Cartesian x/y/z, first and second order) and laplacian
against MATLAB @ballfun at probe points inside the unit ball.
References generated by matlab_harness/refs/ballfun_calculus_refs.m.
"""

from __future__ import annotations

from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

jax.config.update("jax_enable_x64", True)

_REF_PATH = (Path(__file__).resolve().parents[1] / "references"
             / "ballfun_calculus.mat")
if not _REF_PATH.exists():
    pytest.skip(
        "ballfun_calculus.mat golden ref not generated "
        "(run matlab_harness/refs/ballfun_calculus_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)

RTOL = 1e-12
_R = np.atleast_1d(_REF["r"]).astype(float)
_LM = np.atleast_1d(_REF["lm"]).astype(float)
_TH = np.atleast_1d(_REF["th"]).astype(float)


def _eval_pts(g):
    out = []
    for r, lm, th in zip(_R, _LM, _TH):
        v = g.fevalm(jnp.array([r]), jnp.array([lm]), jnp.array([th]))
        out.append(complex(v[0, 0, 0]).real)
    return np.array(out)


@pytest.mark.matlab
class TestBallfunCalculusVsMatlab:
    def test_polynomial_gradient_and_laplacian(self):
        from chebfunjax.ballfun import Ballfun

        f = Ballfun.from_function(lambda x, y, z: x * y + z**2)
        fx, fy, fz = f.grad()
        npt.assert_allclose(_eval_pts(fx), _REF["f1_dx"], rtol=RTOL,
                            atol=1e-13)
        npt.assert_allclose(_eval_pts(fy), _REF["f1_dy"], rtol=RTOL,
                            atol=1e-13)
        npt.assert_allclose(_eval_pts(fz), _REF["f1_dz"], rtol=RTOL,
                            atol=1e-13)
        npt.assert_allclose(_eval_pts(f.laplacian()), _REF["f1_lap"],
                            rtol=RTOL, atol=1e-12)

    def test_transcendental_derivatives(self):
        from chebfunjax.ballfun import Ballfun

        f = Ballfun.from_function(
            lambda x, y, z: jnp.sin(2 * x) * jnp.exp(y) * jnp.cos(z))
        npt.assert_allclose(_eval_pts(f.diff(1)), _REF["f2_dx"], rtol=1e-11)
        npt.assert_allclose(_eval_pts(f.diff(2)), _REF["f2_dy"], rtol=1e-11)
        npt.assert_allclose(_eval_pts(f.laplacian()), _REF["f2_lap"],
                            rtol=1e-10)

    def test_second_derivative(self):
        from chebfunjax.ballfun import Ballfun

        f = Ballfun.from_function(lambda x, y, z: x**2 * z**3)
        npt.assert_allclose(_eval_pts(f.diff(3, 2)), _REF["f3_dzz"],
                            rtol=RTOL, atol=1e-12)
