#!/usr/bin/env python3
"""Sync example pages from the Chebfun originals.

This imports the page header and content from chebfun.org example pages,
rewrites image URLs for the chebfunjax docs layout, and downloads all
referenced PNG assets into docs/images/<category>.
"""

from __future__ import annotations

import argparse
import html
import re
import urllib.parse
import urllib.request
from html.parser import HTMLParser
from pathlib import Path


PROJECT = Path(__file__).resolve().parent.parent
DOCS_EXAMPLES = PROJECT / "docs" / "examples"
DOCS_IMAGES = PROJECT / "docs" / "images"
EXAMPLE_URL_RE = re.compile(
    r"https?://(?:www\.)?chebfun\.org/examples/([\w-]+)/([\w-]+)\.html"
)


class FragmentExtractor(HTMLParser):
    """Extract raw HTML fragments that match a tag predicate."""

    def __init__(self, predicate):
        super().__init__(convert_charrefs=False)
        self.predicate = predicate
        self.depth = 0
        self.capturing = False
        self.fragments: list[str] = []

    def _attrs_dict(self, attrs):
        return {key: value for key, value in attrs}

    def handle_starttag(self, tag, attrs):
        if not self.capturing and self.predicate(tag, self._attrs_dict(attrs)):
            self.capturing = True
            self.depth = 1
            self.fragments.append(self.get_starttag_text())
            return
        if self.capturing:
            self.depth += 1
            self.fragments.append(self.get_starttag_text())

    def handle_endtag(self, tag):
        if self.capturing:
            self.fragments.append(f"</{tag}>")
            self.depth -= 1
            if self.depth == 0:
                self.capturing = False
                self.fragments.append("\n")

    def handle_startendtag(self, tag, attrs):
        if self.capturing or self.predicate(tag, self._attrs_dict(attrs)):
            self.fragments.append(self.get_starttag_text())

    def handle_data(self, data):
        if self.capturing:
            self.fragments.append(data)

    def handle_entityref(self, name):
        if self.capturing:
            self.fragments.append(f"&{name};")

    def handle_charref(self, name):
        if self.capturing:
            self.fragments.append(f"&#{name};")

    def handle_comment(self, data):
        if self.capturing:
            self.fragments.append(f"<!--{data}-->")

    def get_html(self) -> str:
        return "".join(self.fragments).strip()


def fetch_text(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "chebfunjax-example-sync/1.0"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        charset = resp.headers.get_content_charset() or "utf-8"
        return resp.read().decode(charset, "replace")


def fetch_bytes(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "chebfunjax-example-sync/1.0"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def extract_header_and_content(html_text: str) -> tuple[str, str]:
    header = FragmentExtractor(
        lambda tag, attrs: tag == "div" and attrs.get("class") == "page-header"
    )
    content = FragmentExtractor(
        lambda tag, attrs: tag == "div" and attrs.get("id") == "content"
    )
    header.feed(html_text)
    content.feed(html_text)
    return header.get_html(), content.get_html()


def rewrite_fragment(fragment: str, category: str) -> str:
    fragment = html.unescape(fragment)
    fragment = fragment.replace('src="img/', f'src="../../images/{category}/')
    fragment = fragment.replace("src='img/", f"src='../../images/{category}/")
    fragment = fragment.replace('class="figure"', 'class="figure chebfun-figure"')
    fragment = fragment.replace("class='figure'", "class='figure chebfun-figure'")
    fragment = fragment.replace(f'href="/examples/{category}/"', 'href="../"')
    fragment = fragment.replace(f"href='/examples/{category}/'", "href='../'")
    return fragment


def extract_image_urls(page_url: str, html_text: str) -> list[str]:
    return [
        urllib.parse.urljoin(page_url, src)
        for src in re.findall(r'<img[^>]+src="([^"]+\.png)"', html_text, re.IGNORECASE)
    ]


def write_markdown(path: Path, header_html: str, content_html: str, source_url: str) -> None:
    body = "\n\n".join(part for part in [header_html, content_html] if part)
    text = (
        "<!-- Generated by scripts/sync_chebfun_examples.py. -->\n"
        f"<!-- Source: {source_url} -->\n\n"
        '<div class="chebfun-import">\n'
        f"{body}\n"
        "</div>\n"
    )
    path.write_text(text, encoding="utf-8")


def download_images(category: str, image_urls: list[str]) -> None:
    out_dir = DOCS_IMAGES / category
    out_dir.mkdir(parents=True, exist_ok=True)
    for url in image_urls:
        dest = out_dir / Path(urllib.parse.urlparse(url).path).name
        dest.write_bytes(fetch_bytes(url))


def original_url_for(doc_path: Path) -> str:
    text = doc_path.read_text(encoding="utf-8", errors="replace")
    match = EXAMPLE_URL_RE.search(text)
    if not match:
        raise ValueError(f"No Chebfun example URL found in {doc_path}")
    return match.group(0)


def sync_example(doc_path: Path) -> None:
    category = doc_path.parent.name
    source_url = original_url_for(doc_path)
    html_text = fetch_text(source_url)
    header_html, content_html = extract_header_and_content(html_text)
    header_html = rewrite_fragment(header_html, category)
    content_html = rewrite_fragment(content_html, category)
    write_markdown(doc_path, header_html, content_html, source_url)
    download_images(category, extract_image_urls(source_url, html_text))
    print(f"synced {doc_path.relative_to(PROJECT)}")


def iter_example_docs(paths: list[str]) -> list[Path]:
    if paths:
        return [DOCS_EXAMPLES / f"{path}.md" for path in paths]
    return sorted(path for path in DOCS_EXAMPLES.glob("*/*.md") if path.name != "index.md")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "examples",
        nargs="*",
        help="Example paths like approx/AAAApprox. Defaults to all example docs.",
    )
    args = parser.parse_args()

    for doc_path in iter_example_docs(args.examples):
        sync_example(doc_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
