"""MATLAB golden-reference parity tests for the autodiff (ADChebfun / TreeVar) module.

Pins Chebfun's automatic Frechet differentiation against MATLAB Chebfun's
``@adchebfun`` at rtol 1e-12.  For a nonlinear operator ``N`` and a base
function ``u0`` this pins, at matched sample points:

* **VALUE**  ``N(u0)``            -- the primal chebfun ``w.func``.
* **JACOBIAN action** ``dN[u0](v)`` -- the Frechet derivative applied to a
  perturbation ``v = cos(3x)``.  In MATLAB this is the chebfun
  ``w.jacobian * v`` (operatorBlock/mtimes -> toFunction, the exact analytic
  action).  chebfunjax realises the same action by discretising the
  Frechet-derivative :class:`OperatorBlock` at ``n`` Chebyshev points,
  applying it to ``v``, and rebuilding a Chebfun.
* **LINEARITY** ``w.linearity``   -- 1 = linear, 0 = nonlinear.

Both chebfunjax linearisation paths are exercised against the same golden
values: the operator-overloading path (``adchebfun.linearize_op`` /
``ADChebfun``) and the symbolic-tree path (``treevar.linearize_tree`` /
``TreeVar``).  A wrong Jacobian action is the exact failure mode that breaks
Newton iteration in nonlinear BVP solvers, so any mismatch here is a BUG (do
not widen the tolerance -- report it and xfail the failing case).

Golden ref generated by matlab_harness/refs/autodiff_refs.m
(-> tests/references/autodiff.mat).
"""

from pathlib import Path

import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

import chebfunjax as cj
from chebfunjax.autodiff.adchebfun import ADChebfun, detect_linearity, linearize_op
from chebfunjax.autodiff.treevar import TreeVar, linearize_tree
from chebfunjax.chebfun1d.chebfun import Chebfun
from chebfunjax.domain import Domain
from chebfunjax.operators.blocks import ChebColloc2Disc
from chebfunjax.utils.quadrature import chebpts

_REF_PATH = Path(__file__).resolve().parents[1] / "references" / "autodiff.mat"
if not _REF_PATH.exists():
    pytest.skip(
        "autodiff.mat golden ref not generated (run matlab_harness/refs/autodiff_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)

_DOM = tuple(float(w) for w in _REF["dom"])
_PTS = jnp.asarray(_REF["pts"], dtype=jnp.float64)

RTOL = 1e-12
# Collocation size used to realise the Frechet-derivative OperatorBlock's
# action on v.  Chosen so every operator's action is *fully resolved* while
# differentiation-matrix roundoff stays well below rtol.  n=64 is the sweet
# spot: it resolves the highest-degree chain-rule multipliers in this battery
# (sec^2/sech^2 for tan/tanh need ~66 points) yet keeps the D^2 roundoff of
# the stiff N3 = 0.001*u'' - u^3 small.  Verified empirically across all 13
# operators: worst-case max-abs-err vs MATLAB = 2.7e-14 (n=56 under-resolves
# tan/tanh to ~3e-13; n>=80 lets N3's D^2 roundoff climb to ~1e-13).
_NJAC = 64

# Same operator batteries as matlab_harness/refs/autodiff_refs.m (single-arg
# lambdas matching Chebfun's @(u) ... anonymous-operator convention).
_DIFF_OPS = {
    "L1": lambda u: u.diff() - 2.0 * u,
    "N1": lambda u: u ** 2 - u.diff(),
    "N2": lambda u: u * u.diff() + u.sin(),
    "N3": lambda u: 0.001 * u.diff(2) - u ** 3,
}
_UNARY_OPS = {
    "U_sin": lambda u: u.sin(),
    "U_cos": lambda u: u.cos(),
    "U_tan": lambda u: u.tan(),
    "U_exp": lambda u: u.exp(),
    "U_sinh": lambda u: u.sinh(),
    "U_cosh": lambda u: u.cosh(),
    "U_tanh": lambda u: u.tanh(),
    "U_log": lambda u: u.log(),
    "U_sqrt": lambda u: u.sqrt(),
}
# Unary ops needing a strictly-positive argument use base 2 + sin(2x).
_POS_BASE = {"U_log", "U_sqrt"}


def _base(name):
    """Base function u0 for operator ``name`` (matches the MATLAB ref)."""
    if name in _POS_BASE:
        return cj.chebfun(lambda x: 2.0 + jnp.sin(2.0 * x), domain=_DOM)
    return cj.chebfun(lambda x: jnp.sin(2.0 * x), domain=_DOM)


def _v():
    """Perturbation v = cos(3x) (matches the MATLAB ref)."""
    return cj.chebfun(lambda x: jnp.cos(3.0 * x), domain=_DOM)


def _jac_action(jac):
    """Apply Frechet-derivative OperatorBlock ``jac`` to v; eval at _PTS.

    Discretises the operator at _NJAC Chebyshev-2 points, multiplies by the
    perturbation values, and rebuilds a Chebfun -- the chebfunjax analogue of
    MATLAB's ``jac * v``.
    """
    disc = ChebColloc2Disc(_NJAC, _DOM)
    mat = np.asarray(jac.matrix(disc))
    a, b = _DOM
    xg = 0.5 * (b - a) * np.asarray(chebpts(_NJAC, kind=2)) + 0.5 * (a + b)
    vv = np.asarray(_v()(jnp.asarray(xg, dtype=jnp.float64)))
    cf = Chebfun.from_values(jnp.asarray(mat @ vv, dtype=jnp.float64), Domain(_DOM))
    return np.asarray(cf(_PTS))


def _jac_from_treevar(op, u0):
    """Frechet-derivative OperatorBlock via the symbolic TreeVar path."""
    tv = op(TreeVar(_DOM))
    return linearize_tree(tv.tree, u0, _DOM)


class _ParityChecks:
    """Shared value / Jacobian-action / linearity assertions."""

    def _check_value(self, name):
        u0 = _base(name)
        w = _DIFF_OPS.get(name, _UNARY_OPS.get(name))(ADChebfun(u0))
        got = np.asarray(w.func(_PTS))
        npt.assert_allclose(got, _REF[f"{name}_val"], rtol=RTOL, atol=1e-13)

    def _check_jac_adchebfun(self, name):
        op = _DIFF_OPS.get(name, _UNARY_OPS.get(name))
        # Public API: linearize_op returns the Frechet-derivative OperatorBlock.
        jac = linearize_op(op, _base(name), domain=_DOM)
        got = _jac_action(jac)
        npt.assert_allclose(got, _REF[f"{name}_jac"], rtol=RTOL, atol=1e-12)

    def _check_jac_treevar(self, name):
        op = _DIFF_OPS.get(name, _UNARY_OPS.get(name))
        jac = _jac_from_treevar(op, _base(name))
        got = _jac_action(jac)
        npt.assert_allclose(got, _REF[f"{name}_jac"], rtol=RTOL, atol=1e-12)

    def _check_linearity(self, name):
        op = _DIFF_OPS.get(name, _UNARY_OPS.get(name))
        expected = bool(int(_REF[f"{name}_lin"]))
        w = op(ADChebfun(_base(name)))
        assert bool(w.is_linear) == expected
        assert bool(detect_linearity(op, _base(name), domain=_DOM)) == expected


@pytest.mark.matlab
@pytest.mark.parametrize("name", list(_DIFF_OPS))
class TestADChebfunDifferentialOps(_ParityChecks):
    """Differential operators: value, Jacobian action (both paths), linearity."""

    def test_value(self, name):
        self._check_value(name)

    def test_jacobian_action_adchebfun(self, name):
        self._check_jac_adchebfun(name)

    def test_jacobian_action_treevar(self, name):
        self._check_jac_treevar(name)

    def test_linearity(self, name):
        self._check_linearity(name)


@pytest.mark.matlab
@pytest.mark.parametrize("name", list(_UNARY_OPS))
class TestADChebfunUnaryOps(_ParityChecks):
    """Unary functions f(u): value and chain-rule Jacobian action (both paths)."""

    def test_value(self, name):
        self._check_value(name)

    def test_jacobian_action_adchebfun(self, name):
        self._check_jac_adchebfun(name)

    def test_jacobian_action_treevar(self, name):
        self._check_jac_treevar(name)

    def test_linearity(self, name):
        self._check_linearity(name)
