"""MATLAB golden-reference parity for Spherefun calculus.

Directly cross-validates chebfunjax's Spherefun.laplacian / diff (Opus
4.8) against MATLAB @spherefun (R2025b) output -- complementing the
exact-harmonic-identity unit tests.  References generated by
``matlab_harness/refs/spherefun_calculus_refs.m``.

Added by Claude Opus 4.8.
"""

from __future__ import annotations

from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

jax.config.update("jax_enable_x64", True)

from chebfunjax.spherefun.spherefun import Spherefun  # noqa: E402

_REF_PATH = (
    Path(__file__).resolve().parents[1] / "references"
    / "spherefun_calculus.mat"
)
if not _REF_PATH.exists():
    pytest.skip(
        "spherefun_calculus.mat golden ref not generated "
        "(run matlab_harness/refs/spherefun_calculus_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_LAM = jnp.asarray(_REF["lam"], dtype=jnp.float64)
_TH = jnp.asarray(_REF["th"], dtype=jnp.float64)


@pytest.mark.matlab
class TestSpherefunCalculusVsMatlab:
    def test_degree2_harmonic(self):
        """f = sin(th)^2 cos(2 lam): eval, laplacian, d/dx, d/dy, d/dz."""
        f = Spherefun.from_function(
            lambda lam, th: jnp.sin(th) ** 2 * jnp.cos(2 * lam))
        npt.assert_allclose(np.asarray(f(_LAM, _TH)), _REF["f_eval"],
                            rtol=1e-9, atol=1e-9)
        npt.assert_allclose(np.asarray(f.laplacian()(_LAM, _TH)),
                            _REF["f_lap"], rtol=1e-7, atol=1e-8)
        npt.assert_allclose(np.asarray(f.diff(1)(_LAM, _TH)),
                            _REF["f_dx"], rtol=1e-7, atol=1e-8)
        npt.assert_allclose(np.asarray(f.diff(2)(_LAM, _TH)),
                            _REF["f_dy"], rtol=1e-7, atol=1e-8)
        npt.assert_allclose(np.asarray(f.diff(3)(_LAM, _TH)),
                            _REF["f_dz"], rtol=1e-7, atol=1e-8)

    def test_degree1_z(self):
        """g = cos(th) (= z): laplacian == -2 g, d/dz == -sin(th)^2."""
        g = Spherefun.from_function(lambda lam, th: jnp.cos(th))
        npt.assert_allclose(np.asarray(g.laplacian()(_LAM, _TH)),
                            _REF["g_lap"], rtol=1e-8, atol=1e-9)
        npt.assert_allclose(np.asarray(g.diff(3)(_LAM, _TH)),
                            _REF["g_dz"], rtol=1e-7, atol=1e-8)
