"""MATLAB golden-reference parity tests for the spherefun module.

chebfunjax Spherefun is spherical-native (f(lam, theta), lam in [-pi,pi]
longitude, theta in [0,pi] colatitude), matching MATLAB's 2-argument
spherefun(@(lam,th) ...).  Pins evaluation, sum2 (integral over the sphere)
and numerical rank at rtol 1e-12.  Golden ref generated by
matlab_harness/refs/spherefun_refs.m (-> tests/references/spherefun.mat).
"""

from pathlib import Path

import jax.numpy as jnp
import numpy as np
import numpy.testing as npt
import pytest
import scipy.io

from chebfunjax.spherefun.spherefun import Spherefun

_REF_PATH = Path(__file__).resolve().parents[1] / "references" / "spherefun.mat"
if not _REF_PATH.exists():
    pytest.skip(
        "spherefun.mat golden ref not generated (run matlab_harness/refs/spherefun_refs.m)",
        allow_module_level=True,
    )
_REF = scipy.io.loadmat(str(_REF_PATH), squeeze_me=True)
_LAM = jnp.asarray(_REF["lam"], dtype=jnp.float64)
_TH = jnp.asarray(_REF["th"], dtype=jnp.float64)

# Same spherical battery as matlab_harness/refs/spherefun_refs.m.
_FUNS = {
    1: lambda lam, t: jnp.cos(t),
    2: lambda lam, t: jnp.sin(t) * jnp.cos(lam),
    3: lambda lam, t: jnp.exp(jnp.sin(t) * jnp.cos(lam)),
    4: lambda lam, t: 1 + jnp.sin(t) * jnp.cos(lam) * jnp.cos(t),
}
RTOL = 1e-12


@pytest.mark.matlab
@pytest.mark.parametrize("i", [1, 2, 3, 4])
class TestSpherefunVsMatlab:
    def test_eval(self, i):
        f = Spherefun.from_function(_FUNS[i])
        npt.assert_allclose(np.asarray(f(_LAM, _TH)), _REF[f"f{i}_eval"],
                            rtol=RTOL, atol=1e-12)

    def test_sum(self, i):
        f = Spherefun.from_function(_FUNS[i])
        npt.assert_allclose(float(f.sum()), float(_REF[f"f{i}_sum"]),
                            rtol=RTOL, atol=1e-12)

    def test_rank(self, i):
        f = Spherefun.from_function(_FUNS[i])
        assert int(f.rank) == int(_REF[f"f{i}_rank"])
